---
name: ((deployment-name))

releases:
- name: concourse
  version: ((concourse-release-version))
- name: garden-runc
  version: ((garden-runc-release-version))

instance_groups:
- name: web
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  persistent_disk: 10240
  vm_type: topgun
  stemcell: trusty
  jobs:
  - release: concourse
    name: atc
    properties:
      no_really_i_dont_want_any_auth: true
      log_level: debug
      postgresql_database: atc

  - release: concourse
    name: tsa
    properties: {}

  - release: concourse
    name: postgresql
    properties:
      databases:
      - name: atc
        role: atc
        password: dummy-password

- name: worker
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  vm_type: topgun
  stemcell: trusty
  jobs:
  - release: concourse
    name: groundcrew
    consumes: {baggageclaim: {from: bc}}
    properties:
      # prevent tests from hanging forever
      drain_timeout: 10m

  - release: concourse
    name: baggageclaim
    provides: {baggageclaim: {as: bc}}
    properties: {}

  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true
        network_mtu: 1460


- name: special_worker
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  vm_type: topgun
  stemcell: trusty
  jobs:
  - release: concourse
    name: groundcrew
    consumes: {baggageclaim: {from: special_bc}}
    properties:
      tags: [special]

      # prevent tests from hanging forever
      drain_timeout: 10m

      # add special resource type
      additional_resource_types:
      - type: special-time
        image: /var/vcap/packages/time_resource/rootfs

  - release: concourse
    name: baggageclaim
    properties: {}
    provides: {baggageclaim: {as: special_bc}}

  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        allow_host_access: true
        network_mtu: 1460

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: ((stemcell-version))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
