resource_types:
- name: registry-image-beta
  type: registry-image
  source: {repository: concourse/registry-image-resource}

- name: gcs
  type: registry-image
  source: {repository: frodenas/gcs-resource}

groups:
- name: develop
  jobs:
  - unit
  - dev-image
  - testflight
  - watsjs
  - rc
  - build-rc

- name: images
  jobs:
  - unit-image

jobs:
- name: unit
  public: true
  serial: true
  plan:
  - aggregate:
    - get: concourse
      trigger: true
    - get: unit-image
  - task: yarn-test
    image: unit-image
    file: concourse/ci/tasks/yarn-test.yml
  - aggregate:
    - task: unit
      image: unit-image
      file: concourse/ci/tasks/unit.yml
      input_mapping: {concourse: built-concourse}
    - task: fly-darwin
      file: concourse/ci/tasks/fly-darwin.yml
    - task: fly-windows
      file: concourse/ci/tasks/fly-windows.yml

- name: dev-image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: concourse
      passed: [unit]
      trigger: true
    - get: unit-image
      passed: [unit]
    - get: gdn
      trigger: true
    - get: dumb-init
      trigger: true
    - get: mock-resource
      trigger: true
    - get: registry-image-resource
      trigger: true
    - get: git-resource
      trigger: true
    - get: time-resource
      trigger: true
    - get: builder
  - task: yarn-build
    image: unit-image
    file: concourse/ci/tasks/yarn-build.yml
  - task: build
    image: builder
    privileged: true
    input_mapping: {concourse: built-concourse}
    config:
      platform: linux
      params:
        REPOSITORY: concourse/dev
        DOCKERFILE: concourse/ci/dockerfiles/dev/Dockerfile
      inputs:
      - name: concourse
      - name: dumb-init
      - name: gdn
      - name: mock-resource
      - name: registry-image-resource
      - name: time-resource
      - name: git-resource
      outputs: [{name: image}]
      caches: [{path: cache}]
      run: {path: build}
  - put: dev-image
    params: {image: image/image.tar}
    get_params: {format: oci}

- name: testflight
  public: true
  max_in_flight: 2
  plan:
  - aggregate:
    - get: concourse
      passed: [dev-image]
      trigger: true
    - get: unit-image
      passed: [dev-image]
    - get: dev-image
      passed: [dev-image]
      params: {format: oci}
    - get: postgres-image
      params: {format: oci}
  - task: testflight
    image: unit-image
    privileged: true
    timeout: 1h
    file: concourse/ci/tasks/docker-compose-testflight.yml
    params: {DOCKERFILE: ci/dockerfiles/dev-test/Dockerfile}

- name: watsjs
  public: true
  max_in_flight: 2
  plan:
  - aggregate:
    - get: concourse
      passed: [dev-image]
      trigger: true
    - get: unit-image
      passed: [dev-image]
    - get: dev-image
      passed: [dev-image]
      params: {format: oci}
    - get: postgres-image
      params: {format: oci}
  - task: watsjs
    image: unit-image
    privileged: true
    timeout: 1h
    file: concourse/ci/tasks/docker-compose-watsjs.yml
    params: {DOCKERFILE: ci/dockerfiles/dev-test/Dockerfile}

- name: rc
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: concourse
      passed: [testflight, watsjs]
      trigger: true
    - get: dev-image
      passed: [testflight, watsjs]
    - get: unit-image
      passed: [testflight, watsjs]
  - put: version
    params: {pre: rc}

- name: build-rc
  public: true
  plan:
  - aggregate:
    - get: concourse
      passed: [rc]
      trigger: true
    - get: unit-image
      passed: [rc]
    - get: dev-image
      passed: [rc]
    - get: version
      passed: [rc]
    - get: final-version
      resource: version
      passed: [rc]
      params: {bump: final}
  - aggregate:
    - task: fly-linux
      file: concourse/ci/tasks/fly-build-linux.yml
    - task: fly-windows
      file: concourse/ci/tasks/fly-build-windows.yml
    - task: fly-darwin
      file: concourse/ci/tasks/fly-build-darwin.yml
  - task: hoist-linux-dependencies
    image: dev-image
    file: concourse/ci/tasks/hoist-linux-dependencies.yml
  - aggregate:
    - task: concourse-linux
      image: unit-image
      file: concourse/ci/tasks/concourse-build-linux.yml
    - task: concourse-windows
      file: concourse/ci/tasks/concourse-build-windows.yml
    - task: concourse-darwin
      file: concourse/ci/tasks/concourse-build-darwin.yml
  - task: zero-out-huge-stuff
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: busybox}

      outputs:
      - name: dev-image
      - name: unit-image
      - name: fly-linux
      - name: fly-windows
      - name: fly-darwin
      - name: gdn
      - name: resource-types

      run:
        path: echo
        args: ["Having https://github.com/concourse/concourse/issues/1202 would be nice!"]
  - aggregate:
    - put: linux-rc
      params: {file: concourse-linux/concourse-*.tgz}
    - put: windows-rc
      params: {file: concourse-windows/concourse-*.zip}
    - put: darwin-rc
      params: {file: concourse-darwin/concourse-*.tgz}

- name: unit-image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: concourse
      resource: unit-dockerfile
      trigger: true
    - get: builder
  - task: build
    image: builder
    privileged: true
    config:
      platform: linux
      params:
        REPOSITORY: concourse/unit
        CONTEXT: concourse/ci/dockerfiles/unit
      inputs: [{name: concourse}]
      outputs: [{name: image}]
      caches: [{path: cache}]
      run: {path: build}
  - put: unit-image
    params: {image: image/image.tar}

resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: master

- name: unit-dockerfile
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: master
    paths: [ci/dockerfiles/unit]

- name: dev-image
  type: registry-image-beta
  source:
    repository: concourse/dev
    username: ((docker.username))
    password: ((docker.password))

- name: unit-image
  type: registry-image-beta
  source:
    repository: concourse/unit
    username: ((docker.username))
    password: ((docker.password))

- name: postgres-image
  type: registry-image
  source: {repository: postgres}

- name: dumb-init
  type: github-release
  source:
    owner: Yelp
    repository: dumb-init
    access_token: ((concourse_github_dummy.access_token))

- name: gdn
  type: github-release
  source:
    owner: cloudfoundry
    repository: garden-runc-release
    access_token: ((concourse_github_dummy.access_token))

- name: mock-resource
  type: github-release
  source:
    owner: concourse
    repository: mock-resource
    access_token: ((concourse_github_dummy.access_token))

- name: registry-image-resource
  type: github-release
  source:
    owner: concourse
    repository: registry-image-resource
    access_token: ((concourse_github_dummy.access_token))

- name: git-resource
  type: github-release
  source:
    owner: concourse
    repository: git-resource
    access_token: ((concourse_github_dummy.access_token))

- name: time-resource
  type: github-release
  source:
    owner: concourse
    repository: time-resource
    access_token: ((concourse_github_dummy.access_token))

- name: builder
  type: registry-image
  source: {repository: concourse/builder}

- name: version
  type: semver
  source:
    driver: gcs
    bucket: concourse-artifacts
    json_key: ((concourse_artifacts_json_key))
    key: version

- name: linux-rc
  type: gcs
  source:
    bucket: concourse-artifacts
    json_key: ((concourse_artifacts_json_key))
    regexp: rcs/concourse-(.*)-linux-amd64.tgz

- name: windows-rc
  type: gcs
  source:
    bucket: concourse-artifacts
    json_key: ((concourse_artifacts_json_key))
    regexp: rcs/concourse-(.*)-windows-amd64.zip

- name: darwin-rc
  type: gcs
  source:
    bucket: concourse-artifacts
    json_key: ((concourse_artifacts_json_key))
    regexp: rcs/concourse-(.*)-darwin-amd64.tgz
