groups:
- name: concourse
  jobs:
  - deploy-concourse

resources:
- name: concourse-config
  type: git
  source:
    private_key: {{concourse_config_private_key}}
    uri: {{concourse_config_git_url}}

- name: concourse-release
  type: github-release
  source:
    repository: concourse
    user: concourse

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: {{concourse_deployment_bosh_target}}
    username: {{concourse_deployment_bosh_username}}
    password: {{concourse_deployment_bosh_password}}
    deployment: {{concourse_deployment_bosh_deployment}}
    ignore_ssl: {{concourse_deployment_bosh_ignore_ssl}}

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

# A stemcell update will force the workers to restart
# and will result in a failed build.
# However, the bosh deploy will actually succeed.
# Attempting it a second time should result in a (successful) no-op
jobs:
- name: deploy-concourse
  serial: true
  plan:
  - aggregate:
    - get: concourse-release
      trigger: false
      params:
        globs:
        - concourse-*.tgz
        - garden-linux-*.tgz
    - get: concourse-config
      trigger: true
    - get: aws-stemcell
      trigger: false
  - put: concourse-deployment
    params: &concourse_deployment_params
      manifest: {{concourse_config.manifest_location}}
      releases:
        - concourse-release/concourse-*.tgz
        - concourse-release/garden-linux-*.tgz
      stemcells:
        - aws-stemcell/*.tgz
  - put: concourse-deployment
    conditions: [failure]
    params: *concourse_deployment_params
