---
resources:
- name: concourse-rubinius
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop
    paths: [ci/dockerfiles/rubinius]

- name: concourse-rubinius-image
  type: docker-image
  source:
    repository: concourse/rubinius
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-buildbox-ci
  type: git
  source:
    uri: https://github.com/concourse/concourse-lite.git
    branch: master
    paths: [Dockerfile, box-setup]

- name: concourse-buildbox-ci-image
  type: docker-image
  source:
    repository: concourse/buildbox-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-docs-ci
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop
    paths: [ci/dockerfiles/docs-ci]

- name: concourse-docs-ci-image
  type: docker-image
  source:
    repository: concourse/docs-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-concourse-ci
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop
    paths: [ci/dockerfiles/concourse-ci]

- name: concourse-concourse-ci-image
  type: docker-image
  source:
    repository: concourse/concourse-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-atc-ci
  type: git
  source:
    uri: https://github.com/concourse/atc.git
    paths: [Dockerfile]

- name: concourse-atc-ci-image
  type: docker-image
  source:
    repository: concourse/atc-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-tsa-ci
  type: git
  source:
    uri: https://github.com/concourse/tsa.git
    paths: [Dockerfile]

- name: concourse-tsa-ci-image
  type: docker-image
  source:
    repository: concourse/tsa-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-baggageclaim-ci
  type: git
  source:
    uri: https://github.com/concourse/baggageclaim.git
    paths: [Dockerfile]

- name: concourse-baggageclaim-ci-image
  type: docker-image
  source:
    repository: concourse/baggageclaim-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-testflight
  type: git
  source:
    uri: https://github.com/concourse/testflight.git
    paths: [Dockerfile]

- name: concourse-testflight-image
  type: docker-image
  source:
    repository: concourse/testflight
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-static-golang
  type: git
  source:
    uri: https://github.com/concourse/static-golang.git
    paths: [Dockerfile]

- name: concourse-static-golang-image
  type: docker-image
  source:
    repository: concourse/static-golang
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: ubuntu-15.10
  type: docker-image
  source:
    repository: ubuntu
    tag: "15.10"

- name: golang-1.5
  type: docker-image
  source:
    repository: golang
    tag: "1.5"

jobs:
- name: build-rubinius
  plan:
  - aggregate:
    - get: concourse-rubinius
      trigger: true
      params: {submodules: none}
    - get: ubuntu-15.10
      trigger: true
  - put: concourse-rubinius-image
    params:
      load_base: ubuntu-15.10
      build: concourse-rubinius/ci/dockerfiles/rubinius

- name: build-buildbox-ci
  plan:
  - aggregate:
    - get: concourse-buildbox-ci
      trigger: true
    - get: ubuntu-15.10
      trigger: true
  - put: concourse-buildbox-ci-image
    params:
      load_base: ubuntu-15.10
      build: concourse-buildbox-ci/

- name: build-docs-ci
  plan:
  - aggregate:
    - get: concourse-docs-ci
      trigger: true
      params: {submodules: none}
    - get: concourse-rubinius-image
      passed: [build-rubinius]
      trigger: true
  - put: concourse-docs-ci-image
    params:
      load_base: concourse-rubinius-image
      build: concourse-docs-ci/ci/dockerfiles/docs-ci

- name: build-concourse-ci
  plan:
  - aggregate:
    - get: concourse-concourse-ci
      trigger: true
      params: {submodules: none}
    - get: ubuntu-15.10
      trigger: true
  - put: concourse-concourse-ci-image
    params:
      load_base: ubuntu-15.10
      build: concourse-concourse-ci/ci/dockerfiles/concourse-ci

- name: build-atc-ci
  plan:
  - aggregate:
    - get: concourse-atc-ci
      trigger: true
    - get: ubuntu-15.10
      trigger: true
  - put: concourse-atc-ci-image
    params:
      load_base: ubuntu-15.10
      build: concourse-atc-ci

- name: build-tsa-ci
  plan:
  - aggregate:
    - get: concourse-tsa-ci
      trigger: true
    - get: ubuntu-15.10
      trigger: true
  - put: concourse-tsa-ci-image
    params:
      load_base: ubuntu-15.10
      build: concourse-tsa-ci

- name: build-baggageclaim-ci
  plan:
  - aggregate:
    - get: concourse-baggageclaim-ci
      trigger: true
    - get: golang-1.5
      trigger: true
  - put: concourse-baggageclaim-ci-image
    params:
      load_base: golang-1.5
      build: concourse-baggageclaim-ci

- name: build-testflight
  plan:
  - aggregate:
    - get: concourse-testflight
      trigger: true
    - get: golang-1.5
      trigger: true
  - put: concourse-testflight-image
    params:
      load_base: golang-1.5
      build: concourse-testflight

- name: build-static-golang
  plan:
  - aggregate:
    - get: concourse-static-golang
      trigger: true
    - get: golang-1.5
      trigger: true
  - put: concourse-static-golang-image
    params:
      load_base: golang-1.5
      build: concourse-static-golang
