---
resources:
- name: concourse-rubinius
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop
    paths: [ci/dockerfiles/rubinius]

- name: concourse-rubinius-image
  type: docker-image
  source:
    repository: concourse/rubinius
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-docs-ci
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop
    paths: [ci/dockerfiles/docs-ci]

- name: concourse-docs-ci-image
  type: docker-image
  source:
    repository: concourse/docs-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

- name: concourse-concourse-ci
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop
    paths: [ci/dockerfiles/concourse-ci]

- name: concourse-concourse-ci-image
  type: docker-image
  source:
    repository: concourse/concourse-ci
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}

jobs:
- name: build-rubinius
  plan:
  - get: concourse-rubinius
    params: {submodules: none}
  - put: concourse-rubinius-image
    params: {build: concourse-rubinius/ci/dockerfiles/rubinius}

- name: build-docs-ci
  plan:
  - get: concourse-docs-ci
    params: {submodules: none}
  - put: concourse-docs-ci-image
    params: {build: concourse-docs-ci/ci/dockerfiles/docs-ci}

- name: build-concourse-ci
  plan:
  - get: concourse-concourse-ci
    params: {submodules: none}
  - put: concourse-concourse-ci-image
    params: {build: concourse-concourse-ci/ci/dockerfiles/concourse-ci}
