version: '3.4'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=dev
    - POSTGRES_USER=dev
    - PGDATA=/database

  web:
    build:
      context: .
      dockerfile: dev/Dockerfile
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=db
    - CONCOURSE_POSTGRES_USER=dev
    - CONCOURSE_POSTGRES_PASSWORD=dev
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://localhost:8080
    - CONCOURSE_ADD_LOCAL_USER=test:test
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_TSA_HEARTBEAT_INTERVAL=5s
    - CONCOURSE_LOG_LEVEL=debug

  worker:
    build:
      context: .
      dockerfile: dev/Dockerfile
    command: worker
    privileged: true
    depends_on: [web]
    ports: ["7777:7777", "7788:7788"]
    environment:
    - CONCOURSE_TSA_HOST=web:2222
    - CONCOURSE_EPHEMERAL=true
