---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ((image-resource-repository))}

params:
  SECRET: ((task-secret))

run:
  path: sh
  args: ['-c', 'echo SECRET: $SECRET']
