---
name: ((deployment_name))

releases:
- name: concourse
  version: ((concourse_release_version))
- name: bpm
  version: ((bpm_release_version))
- name: postgres
  version: ((postgres_release_version))

instance_groups:
- name: concourse
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  persistent_disk: 10240
  vm_type: topgun
  stemcell: xenial
  jobs:
  - release: bpm
    name: bpm

  - release: concourse
    name: web
    properties:
      token_signing_key: ((token_signing_key))

      add_local_users:
      - some-user:$2a$10$ElspuoVbekkuIlqvk25HN.9DRwGpkS0mUluTjrhsOMKhcGKNUHHvC
      - some-other-user:$2a$10$ElspuoVbekkuIlqvk25HN.9DRwGpkS0mUluTjrhsOMKhcGKNUHHvC

      main_team:
        auth:
          local:
            users: [some-user]

      log_level: debug

      postgresql:
        database: &db-name atc
        role: &db-role
          name: atc
          password: dummy-password

      worker_gateway:
        host_key: ((tsa_host_key))
        token_signing_key: ((token_signing_key))
        authorized_keys: [((worker_key.public_key))]

  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db-name
        roles:
        - *db-role

- name: worker
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  vm_type: topgun
  stemcell: xenial
  jobs:
  - release: concourse
    name: worker
    properties:
      worker_gateway: {worker_key: ((worker_key))}

      # prevent tests from hanging forever
      drain_timeout: 10m

- name: other_worker
  instances: 1
  networks: [{name: topgun}]
  azs: [z1]
  vm_type: topgun
  stemcell: xenial
  jobs:
  - release: concourse
    name: worker
    properties:
      worker_gateway: {worker_key: ((worker_key))}

      # prevent tests from hanging forever
      drain_timeout: 10m

variables:
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: ((stemcell_version))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
