---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: concourse
- name: version
- name: concourse-bosh-release
- name: linux-rc
- name: windows-rc

outputs:
- name: bumped-concourse-bosh-release

params:
  BOSH_PRIVATE_CONFIG:

run:
  path: concourse/ci/tasks/scripts/bump-concourse-blob
