---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/concourse-rc
    tag: latest

inputs:
- name: helm-chart
- name: concourse

run:
  path: concourse/ci/tasks/scripts/check-helm-chart-parameters
