---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: concourse
- name: fly-rc
- name: version
- name: final-version

outputs:
- name: bosh-rc

run:
  path: concourse/ci/tasks/scripts/create-bosh-rc
