---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/atc-ci

inputs:
- name: concourse
- name: fly-rc

params:
  WEB_IP:
  WEB_USERNAME:
  WEB_PASSWORD:
  PIPELINE_NAME:

run:
  path: concourse/ci/tasks/scripts/create-uber-pipeline
