---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: concourse-head
- name: version
- name: bosh-rc

outputs:
- name: final-release-repo
- name: final-release-tarball

run:
  path: concourse-head/ci/tasks/scripts/finalize-release
