---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse

caches:
- path: concourse/web/node_modules
- path: concourse/web/elm/elm-stuff

outputs:
- name: built-concourse

run:
  path: concourse/ci/tasks/scripts/make
