---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu

inputs:
  - name: concourse
  - name: garden-runc

outputs:
  - name: renamed-release

run:
  path: concourse/ci/tasks/scripts/rename-release
