---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: concourse
- name: web

outputs:
- name: bosh-dev

run:
  path: concourse/ci/tasks/scripts/web-pr
