---
name: concourse

director_uuid: <%= `bosh status --uuid` %>

# fill in with jobs and resources
pipeline: &pipeline
  resources: []

  jobs:
    - name: dummy
      config:
        image: docker:///busybox
        run:
          path: echo
          args: [Hello, world!]

web_ips: &web-ips
  - 10.244.8.2

atc_db: &atc-db atc
atc_role: &atc-role
  name: atc
  password: dummy-postgres-password

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

jobs:
  - name: web
    instances: 1
    resource_pool: concourse
    networks:
      - name: concourse
        static_ips: *web-ips
    persistent_disk: 1024 # for consul
    templates:
      - {release: concourse, name: atc}
      - {release: concourse, name: consul-agent}
    properties:
      atc:
        pipeline: *pipeline
        development_mode: true
        postgresql:
          database: *atc-db
          role: *atc-role

      consul:
        agent:
          mode: server
          servers: {lan: *web-ips}

  - name: db
    instances: 1
    resource_pool: concourse
    networks: [{name: concourse}]
    persistent_disk: 10240
    templates:
      - {release: concourse, name: postgresql}
      - {release: concourse, name: consul-agent}
    properties:
      postgresql:
        databases: [{name: *atc-db}]
        roles: [*atc-role]

      consul:
        agent:
          services: [{name: postgresql}]
          servers: {lan: *web-ips}

  - name: worker
    instances: 1
    resource_pool: concourse
    networks: [{name: concourse}]
    templates:
      - {release: concourse, name: turbine}
      - {release: garden-linux, name: garden}
      - {release: concourse, name: consul-agent}
    properties:
      garden:
        # cannot enforce quotas in bosh-lite
        disk_quota_enabled: false

      consul:
        agent:
          services: [{name: turbine}]
          servers: {lan: *web-ips}

networks:
  - name: concourse
    subnets:
      # networks with static ips used for web instances
      - range: 10.244.8.0/30
        reserved: [10.244.8.1]
        static: [10.244.8.2]
        cloud_properties: {}
      - range: 10.244.8.4/30
        reserved: [10.244.8.5]
        static: [10.244.8.6]
        cloud_properties: {}
      - range: 10.244.8.8/30
        reserved: [10.244.8.9]
        static: [10.244.8.10]
        cloud_properties: {}

      # networks for dynamic ips (db, workers, compilation vms)
      - range: 10.244.16.4/30
        reserved: [10.244.16.5]
        cloud_properties: {}
      - range: 10.244.16.8/30
        reserved: [10.244.16.9]
        cloud_properties: {}
      - range: 10.244.16.12/30
        reserved: [10.244.16.13]
        cloud_properties: {}
      - range: 10.244.16.16/30
        reserved: [10.244.16.17]
        cloud_properties: {}
      - range: 10.244.16.20/30
        reserved: [10.244.16.21]
        cloud_properties: {}

resource_pools:
  - name: concourse
    network: concourse
    cloud_properties: {}
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

compilation:
  workers: 3
  network: concourse
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
