---
name: concourse

releases:
- name: concourse
  version: 0+dev.1
  url: file:///vagrant/dev_releases/concourse-0+dev.1.tgz

networks:
- name: concourse
  type: dynamic

compilation:
  network: concourse

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 10

jobs:
- name: atc
  instances: 1

  templates:
  - name: atc
    release: concourse
  - name: turbine
    release: concourse
  - name: glider
    release: concourse
  - name: redis
    release: concourse
  - name: warden
    release: concourse

  networks:
  - name: concourse

  properties:
    network_name: concourse
    atc:
      config:
        jobs:
        - name: dummy
          image: ubuntu
          script: |
            echo 'Hello, world!'

      turbine:
        address: 127.0.0.1:4637

      redis:
        address: 127.0.0.1:6379

    glider:
      turbine:
        address: 127.0.0.1:4637

    turbine:
      warden:
        address: 127.0.0.1:7777
        network: tcp

    warden:
      disk_quota_enabled: false
      kernel_network_tuning_enabled: false
      listen_address: 0.0.0.0:7777
      listen_network: tcp
