---
- type: replace
  path: /instance_groups/name=concourse/jobs/name=atc/properties/ssm?
  value:
    aws_region: ((aws_region))
    aws_access_key: ((aws_access_key))
    aws_secret_key: ((aws_secret_key))
    aws_session_token: ((aws_session_token))
    secret_template: /concourse-topgun/{{.Team}}/{{.Pipeline}}/{{.Secret}}
    fallback_secret_template: /concourse-topgun/{{.Team}}/{{.Secret}}
