groups: []

resources:
- name: timestamp
  type: time

jobs:
- name: do-in-agg
  plan:
  - aggregate:
    - do:
      - task: agg-do-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: agg-do-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: agg-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: agg-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: agg-3
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    ensure:
      task: agg-ensure
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}

- name: putgets
  plan:
  - aggregate:
    - do:
      - task: agg-task
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      ensure:
        task: do-ensure
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: agg-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: agg-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: agg-3
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - put: timestamp

- name: agg-in-do
  plan:
  - do:
    - task: do-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - aggregate:
      - task: do-agg-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: do-agg-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: do-agg-3
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: do-3
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - do:
      - task: do-do-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: do-do-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    ensure:
      task: do-ensure
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}

- name: all-the-things
  plan:
  - aggregate:
    - task: vanilla-agg-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: vanilla-agg-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    ensure:
      task: agg-ensure
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - do:
    - task: vanilla-do-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: vanilla-do-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - do:
    - task: do-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - aggregate:
      - task: do-agg-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: do-agg-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      ensure:
        task: agg-ensure
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: do-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    ensure:
      task: do-ensure
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - do:
    - aggregate:
      - task: agg-first-do-agg-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: agg-first-do-agg-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      ensure:
        task: agg-ensure
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: agg-first-do-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: agg-first-do-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    ensure:
      task: do-ensure
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - aggregate:
    - task: agg-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - do:
      - task: agg-do-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: agg-do-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: agg-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - aggregate:
    - do:
      - task: do-first-agg-do-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: do-first-agg-do-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - task: do-first-agg-1
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
    - task: do-first-agg-2
      config:
        platform: linux
        image: docker:///busybox
        run: {path: sleep, args: [1]}
  - aggregate:
    - do:
      - task: agg-with-do-only-1-do-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: agg-with-do-only-1-do-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
    - do:
      - task: agg-with-do-only-2-do-1
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
      - task: agg-with-do-only-2-do-2
        config:
          platform: linux
          image: docker:///busybox
          run: {path: sleep, args: [1]}
