---
resource_types:
- name: my-time
  type: docker-image
  source: {repository: concourse/time-resource}

resources:
- name: 10m
  type: my-time
  source: {interval: 1h}

jobs:
- name: get-10m
  plan:
  - get: 10m
  - task: fail
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: busybox}

      run:
        path: "false"
