resources:
- name: some-repo
  type: git
  source:
    uri: {{some-repo-uri}}

jobs:
- name: simple-job
  plan:
  - get: some-repo
  - task: wait
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sh
        args:
        - -c
        - |
          until test -f /tmp/stop-waiting; do
            echo 'waiting for /tmp/stop-waiting to exist'
            sleep 1
          done

          echo done
