resource_types:
- name: fake-resource-type
  type: docker-image
  source:
    access_token: resource_type_secret

resources:
- name: fake-resource
  type: fake-resource-type
  source:
    uri: git@github.com:concourse/git-resource.git
    branch: master
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAtCS10/f7W7lkQaSgD/mVeaSOvSF9ql4hf/zfMwfVGgHWjj+W
      resource_secret
      DWiJL+OFeg9kawcUL6hQ8JeXPhlImG6RTUffma9+iGQyyBMCGd1l
      -----END RSA PRIVATE KEY-----

jobs:
- name: simple-job
  plan:
  - get: fake-resource
  - task: simple-task
    file: fake-resource/file.yml
    params:
      SECRET: job_secret
