---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: e7afa101-925b-4cb5-8c12-831e5d097574
  sha: !binary |-
    NzU2ZmVlYzQ5MDI1YTYwMDQyMWQ3YWU3ZTM0MjAxZTMwYWRmMjdmZQ==
  size: 2549492
resources/time-resource.tar.gz:
  object_id: 7ff8a7a3-d488-4622-9940-dee4a9f7e279
  sha: !binary |-
    ZjA5NTc4NzYzMTdlYTE4MDZkYmMxNWVlZmIzM2U4OGZhYWUwODY0Mw==
  size: 2518561
resources/semver-resource.tar.gz:
  object_id: 23250d86-0b38-4af6-a2e0-5bf504e2d57e
  sha: !binary |-
    ZjY1NzhmNWY3M2Y2ZWE2NDI0MWQxOWViNDBjM2I4ZDM5MWY2OTg1ZQ==
  size: 8618181
resources/s3-resource.tar.gz:
  object_id: 0ee4daba-f878-4b75-921a-95bb7c9bb988
  sha: !binary |-
    YTVlYjA4YTFhNTk4ZDk1ZGVjOWYzNzE2ZmM4MjVhZDVlMTdkOTFiMw==
  size: 8830227
resources/tracker-resource.tar.gz:
  object_id: a157322d-4d13-4f75-8cfa-60fcce1c92b6
  sha: !binary |-
    ZTk4NjljODZjZWRhZmM5NDhmYzU4MjI1MTZhNTA1M2MzMDZmZjM3Ng==
  size: 11537368
resources/git-resource.tar.gz:
  object_id: 7b63591c-dfba-4cf5-bf89-c95822469d5e
  sha: !binary |-
    YTcyNWMzODE5NmNkM2Q2NDUwNTRjNjViMDY4NmU4ZDY5YWNkNWY0OQ==
  size: 9155172
resources/docker-image-resource.tar.gz:
  object_id: b520777a-e97b-4a19-9c9f-744da00a4e76
  sha: !binary |-
    NzYxNmU0NTRjZGJjZDY0YzUxY2I0ODAxOTZiY2JmNjAyYTE4ZmIxNA==
  size: 8277120
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: e3f29890-33a5-4768-af55-d6847537b39f
  sha: !binary |-
    YzIwYzNhODgzYmE4MjI3OGNmMTAxYzg3ODEyYTRiOGQ3ZjhlYzFmNg==
  size: 9154791
resources/cf-resource.tar.gz:
  object_id: c3937814-1513-4799-8af9-6e04142d66eb
  sha: !binary |-
    OTBhZjk3NWFiYzJkNTg5OTBiYTliYTdhYTI2MzY4N2M5YjBjNDQzMQ==
  size: 12629319
resources/github-release-resource.tar.gz:
  object_id: c292f3df-9bec-4c6c-92c0-f4ff7c62ae9a
  sha: !binary |-
    YWU1Y2MzYTRkYjFmMjBkNDViMmMwNzcwMjA4MTgxZTY2YjI2ZjA2Yg==
  size: 6776962
