---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: c3ccf92b-bb6b-4fe9-b1c8-3761c7118ba2
  sha: !binary |-
    MjNlN2NiY2I4ZjkzNTliMWI3ZmE4NDlmNTBmNGNhYmQ4OTBmMDBiMg==
  size: 2549624
resources/time-resource.tar.gz:
  object_id: 0096f331-17f4-4b73-88b3-af1a5df15b76
  sha: !binary |-
    MWU5ZjY1MTgwZjRkZWE3NWI1YjdhMWQ0MTNmZjYwZWUzOTA3OTI5ZA==
  size: 2518572
resources/semver-resource.tar.gz:
  object_id: 50b33e18-5d5a-4f5d-ab2c-456ca1ca764f
  sha: !binary |-
    MDQwYjMxMzM3NzcxNTc1M2RlODg1NTYzNGQ3NzY1OTFkOWZiMDg1Nw==
  size: 8619006
resources/s3-resource.tar.gz:
  object_id: 0458de9f-73d8-49f2-a86f-b052d85f593a
  sha: !binary |-
    MTQ5NTFhODRkNGM1OTdiMDRmZDQ2ZWRhYTQ1M2Q5NGZlZTgxZDViZQ==
  size: 8829477
resources/tracker-resource.tar.gz:
  object_id: 9ad7a288-6a9d-4476-8032-7e1333e23fa4
  sha: !binary |-
    YjFjYjM3NmNhNjY3MjU1YjdlMDlkOThjZTgzMjgwMWY3YzNjNWFiNA==
  size: 9882086
resources/git-resource.tar.gz:
  object_id: 8ab75578-2152-42b7-823f-221a65e169f2
  sha: !binary |-
    NDQ3NzE3ZThlNzEwZmFlMDZjZDgzODE2NzJiYmUyMDFmMWJhODczYQ==
  size: 7505277
resources/docker-image-resource.tar.gz:
  object_id: b3f1c818-7e9a-4a34-b527-38deb66b6f5c
  sha: !binary |-
    NzFkODlkNmM5NzQ0ODg3ZDM0NWMzN2I1NWNjN2I2N2Y2Nzk1YWEzZQ==
  size: 8277135
resources/vagrant-cloud-resource.tar.gz:
  object_id: 48e09904-8b92-46b0-82fc-dd6f0ad7c6df
  sha: !binary |-
    ZTE2MWE0NjU0ZTAyOTc1NGQ0YzQzNWUxNjc0ZTczNDUzYTYzMWMyNw==
  size: 7502611
resources/cf-resource.tar.gz:
  object_id: d423e023-c55d-48a1-a948-42e2b08a5203
  sha: !binary |-
    MDk2NmIxMGY0OTgwNjAyYzAzNDJkMTA4YjU2NTU5MTNjNTcwNWFmNQ==
  size: 12628209
resources/github-release-resource.tar.gz:
  object_id: f4c1fee9-fc9a-4572-a6f5-e54d65face9d
  sha: !binary |-
    ZWMyOGYzODZiYWIzY2RjZjkwYmJiNmUwNTE4ODUyNWYyNTI2MmI0ZQ==
  size: 8835115
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
