---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: 92348b2f-3f70-4c97-a7d2-eba498963e2b
  sha: !binary |-
    MDcwZTRmYzg2ZDY4MWVkODE1M2JjODUyNjhlZTU0OTcwZDEyNGUzZA==
  size: 10428189
resources/time-resource.tar.gz:
  object_id: b48c0438-287b-4291-8a79-c856c96d1293
  sha: !binary |-
    MjNlMWJiODNjMzhlYzM3MDliMWZhYzY1ZWI5ZjFmOTgxMzBjNmQ1Ng==
  size: 2459242
resources/semver-resource.tar.gz:
  object_id: 67a3b8cc-26fe-4794-9ae1-26f2a4976d20
  sha: !binary |-
    ZWRjYzg3MTQ4YWI5NmIwZTYxZjJjMTIxOTFmM2QzNmIxNGYzMWE5Mw==
  size: 14766068
resources/s3-resource.tar.gz:
  object_id: a2b683c7-8130-4039-b11d-f1ff6d9f86cd
  sha: !binary |-
    MTg4N2FjOGZhZDAxMjMzOWRiYTA0MTY2NTJiZjg4ZDQ2ZmNlNWNmMw==
  size: 10997023
resources/tracker-resource.tar.gz:
  object_id: 291f6191-c6f4-486d-a8c0-971e35404d2a
  sha: !binary |-
    MTY3OWVhYTFjN2FiNGIwYzAyMWNlMDIwM2ZjYjQwZmVlZDVhNjFlOA==
  size: 12653472
resources/git-resource.tar.gz:
  object_id: a8632980-84bc-4687-ac08-44651b2c6952
  sha: !binary |-
    YTI3YzBlYzM5MGRiNzc1YjYzZDkzMWUzZDlkYzU5ZmYyN2UyNjNkOA==
  size: 8779812
resources/docker-image-resource.tar.gz:
  object_id: 4b29dddf-5c0f-4197-8953-babdd0cd79e5
  sha: !binary |-
    MTc4NTg5NDMxMzM4ZGM0Y2I4NjlmMzA1NmQ2YmY2YTVhNTNkYmVlZA==
  size: 10044837
resources/vagrant-cloud-resource.tar.gz:
  object_id: 3c17d93c-fdb3-4716-9102-3a19a923e14c
  sha: !binary |-
    MGQ1MGU4Y2Q0Y2ZhZjliOTM3NTQzNDAyYTRiZjdjZDllZDY1YTNkNQ==
  size: 8778654
resources/cf-resource.tar.gz:
  object_id: a3b2aee8-356d-4a13-a9b9-d2ce3346f004
  sha: !binary |-
    NjBkZWI2YjBlOTNjZTYwZTE0YjVkOGExN2Q0Y2QzNTVmYzg3MWUwZg==
  size: 16187357
resources/github-release-resource.tar.gz:
  object_id: 7056b01f-af6a-4148-ad35-089a2c4fbea9
  sha: !binary |-
    ZWU3ZWMxMDFhYmIzYjhhYTMwNWJiMjNhYTA1NDliMTQzYzg5Y2ZmZg==
  size: 10121737
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: be0933a0-c0be-4ac7-a59c-bae77fa16705
  sha: !binary |-
    Y2I3Y2E3YThkYWE0OGZkYTFkYTVlYjYxMmZkMTRkNGY4NGMxMjUyOA==
  size: 8779768
resources/bosh-io-release-resource.tar.gz:
  object_id: 0d643139-9758-447c-a361-818bcc4d7e66
  sha: !binary |-
    NTQyMWUyNzE2OGI2MmVjMzk3ZWYzOWQ1MTNiNzhmN2JhOWQ2YjNhOA==
  size: 8778866
resources/bosh-deployment-resource.tar.gz:
  object_id: 1037bfd6-f9d6-4d58-b1ab-0b6d81cdf52c
  sha: !binary |-
    ZGZlZDc5ZGM0NDc1OWMwZTMzOTBhMTdlYWIxODQ3N2MxZTAxZjA2OQ==
  size: 22425932
btrfs_tools_3.12/btrfs:
  object_id: 8a522cff-b202-43a6-8d10-7e68c473f66e
  sha: 5d7afc7cff4e2d842dcc22129799b1329ed2e868
  size: 353424
btrfs_tools_3.12/mkfs.btrfs:
  object_id: 25651d29-52e3-4441-afc0-b590ea64c410
  sha: 80108e80d404d8fdd435703f8526ff8a44e4bbe2
  size: 171728
resources/pool-resource.tar.gz:
  object_id: 151d5cf3-23c7-4dcb-a49d-e3f1e98e325a
  sha: !binary |-
    OGQ1YjRiNzFjY2JmZjYxZGZmNDQ3ZjNlNjg2MzY1YWY0MWIxNTU3Ng==
  size: 9611857
golang_1.5/go1.5.1.linux-amd64.tar.gz:
  object_id: 6fe7cb89-c844-4191-a791-01a1625526ab
  sha: 46eecd290d8803887dec718c691cc243f2175fe0
  size: 77875767
