---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: 0aad7e44-d383-4b44-99d5-fbbbbfbbf51c
  sha: !binary |-
    ZWYyNDExYjc5YWMyNzI5ZDY1NjljZTY4Njc2YjM3M2FiOTJhY2U4OA==
  size: 2549734
resources/time-resource.tar.gz:
  object_id: 73db0c47-0f5f-4a69-8436-ae3c207d5b9f
  sha: !binary |-
    ZWE4MGUzODJmZGU5N2YyMTg2ZjcxMDBiZjJlNWJkZTY4ZDY3NzMyMQ==
  size: 2518572
resources/semver-resource.tar.gz:
  object_id: 0c4d10a1-6ed2-4bcb-970a-684a8078530c
  sha: !binary |-
    MGVkMWY4MTAxMDk4ODU0Mjg2NDdkNWI1ZGEyMzdiNDJlZmZlM2ZkZg==
  size: 8626835
resources/s3-resource.tar.gz:
  object_id: 9746d831-c7d7-47d6-95f0-3b4fabbcae3f
  sha: !binary |-
    ZjJkNzViZTBjMDc1MGIxZDg4MmIxZTg3OGNiMTdhNzM2OGMwMTg5ZA==
  size: 8830309
resources/tracker-resource.tar.gz:
  object_id: f8c1d8d2-08d0-4442-b8ac-1c5bc347c96f
  sha: !binary |-
    ZTY4YmVlMjgwYzY4MDlkMzlhNjg4YjQ5ODZlNmY1NjdhMDA4ZGVkMA==
  size: 11532746
resources/git-resource.tar.gz:
  object_id: 8b093ed6-48f3-4717-9957-99139b6ae00e
  sha: !binary |-
    N2JhM2NkNTdmOGNjYWE0ZjIxNmZkMGNmNTdkNjI2ODM4YmE1OTk4Zg==
  size: 9155208
resources/docker-image-resource.tar.gz:
  object_id: 0cee8784-d514-49ae-8dc3-23bc48218549
  sha: !binary |-
    ZjAzMzQ3NThlNTY1N2Q2NTVmODQzYjBhYjgxODk0MGJiZWNlOTM4Ng==
  size: 7953837
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: ae5f62b8-3e54-4294-aef5-7c00540754c5
  sha: !binary |-
    ODBkMDI3MTQwOTVkOWJkZGE3ZGI3NDMxZjI2MzBkM2Q2YTc5MGVmYQ==
  size: 9154754
