---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: !binary |-
    YjZiMTU0OTMzMDM5OTg3MDU2YWMzMDdlMjBjMjVmYTUwOGEwNmJhNg==
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: !binary |-
    OWY4MGIzY2ZlYmM0MzRjYTA4NjBmYzg0ODk5MjNjZWE3MzQ1NjA4MQ==
  size: 21865589
consul_0.3/consul:
  object_id: 03a93976-87ff-4d84-92b9-b03e0f979720
  sha: !binary |-
    NDhiOWI2NzFmNzU0NzliZWJjZTczOGYzMDY1NGUxODUyMGQ5NGM5Ng==
  size: 14388499
resources/archive-resource.tar.gz:
  object_id: 401b3cbf-8391-44e7-b6ac-0c39622c6dd2
  sha: !binary |-
    MGQ0NjQzYTgzMzU2MjJhNjQ0N2IxZWIyMDI2ZGE1NDlkN2IxOGNkYQ==
  size: 2549733
resources/time-resource.tar.gz:
  object_id: 0ccb7f9e-cac0-4e6c-9362-cbf13cbd3742
  sha: !binary |-
    MjlkNWZmZTA2YzU4ZmEzOGY2NjU0NmExMWRiYjBiMzQ0YzJiNjg5ZA==
  size: 2518560
resources/semver-resource.tar.gz:
  object_id: c655d47c-cdce-4f7e-b002-9d8cd8c88d3f
  sha: !binary |-
    Y2ExOTYwMzI3Y2VlYzlhODNmOGQyYWU1MTlmMWM4ZTMyNGI0ODMyZg==
  size: 8606971
resources/s3-resource.tar.gz:
  object_id: 0550cdbc-318a-4a6a-a4f4-50b8d297b745
  sha: !binary |-
    MTAzNzNlYzNjZDNlYmExZDAzNGQxYWNjODdhZGZkMDlhMGQ4MWI0Ng==
  size: 8807547
resources/tracker-resource.tar.gz:
  object_id: ff5e5855-df1b-42a7-b9ca-4c52dded62f7
  sha: !binary |-
    ZWU5YWJlN2Q4ZTg2M2RhYTNkZTI4NjU2MTMyMjkyYzhmMzNiOTMxZg==
  size: 11391225
resources/git-resource.tar.gz:
  object_id: 39886aac-ad4c-4cf2-9740-6f888fb1c053
  sha: !binary |-
    MmFkMTUyM2QzNjBkZGNiZjgyMTc4ZjIxZDA1YTEyNzkxYTlmNjdhNA==
  size: 9154815
resources/docker-image-resource.tar.gz:
  object_id: 11d17229-e60a-487f-a9f3-b80e6f5ae2b2
  sha: !binary |-
    MmQ3ZWVjYWQxMWM0ZmE2MmZmNTk4NWZmYmUxMjFmYTkzMGE3MzQzNA==
  size: 7761648
