---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: 77ac3c75-b63d-46c8-bce1-fe3966a25e2e
  sha: !binary |-
    MjJlZDc2ZTI3MzkyOGVmYmI2MDg3OTU5ZTJmNDAyYTQyOWVmN2ZlYQ==
  size: 10427949
resources/time-resource.tar.gz:
  object_id: b48c0438-287b-4291-8a79-c856c96d1293
  sha: !binary |-
    MjNlMWJiODNjMzhlYzM3MDliMWZhYzY1ZWI5ZjFmOTgxMzBjNmQ1Ng==
  size: 2459242
resources/semver-resource.tar.gz:
  object_id: e43e605c-2aac-4ee2-835f-8429804a5d2e
  sha: !binary |-
    ZTMwMTk4M2RlMWMxNjFjYmRlMzI1ODlkNDZkNzhkOTY1ZWIyOWVjYg==
  size: 8954191
resources/s3-resource.tar.gz:
  object_id: da336866-ea28-4857-bc66-bf80e8742fcd
  sha: !binary |-
    YjBlNDgxYzA5MWY0ZTU2NzMzMGM1MDYwYTU1YzRiYmViZGIzZjEyZg==
  size: 9965868
resources/tracker-resource.tar.gz:
  object_id: 291f6191-c6f4-486d-a8c0-971e35404d2a
  sha: !binary |-
    MTY3OWVhYTFjN2FiNGIwYzAyMWNlMDIwM2ZjYjQwZmVlZDVhNjFlOA==
  size: 12653472
resources/git-resource.tar.gz:
  object_id: 906b5d66-6ef9-4e91-bc36-d037d5d2e007
  sha: !binary |-
    OWFlZTY0MjU0MmQ1Yzc5NTc5MmJhYzRkNjMzMWQ2N2M2MDAyMTU2Zg==
  size: 8779834
resources/docker-image-resource.tar.gz:
  object_id: 234f9494-dc27-4e73-a3af-9ea2783853ce
  sha: !binary |-
    ZTlmZTFhNDZmMzFhNGJiYWFiNmM3MTVkOWE4NDU3M2I3ZGZjZjdkZg==
  size: 10044409
resources/vagrant-cloud-resource.tar.gz:
  object_id: 3c17d93c-fdb3-4716-9102-3a19a923e14c
  sha: !binary |-
    MGQ1MGU4Y2Q0Y2ZhZjliOTM3NTQzNDAyYTRiZjdjZDllZDY1YTNkNQ==
  size: 8778654
resources/cf-resource.tar.gz:
  object_id: 2b386dfe-b123-4e73-988e-bece279fa7ed
  sha: !binary |-
    NzU1NDE5ODY1OTYxOTE1M2I2OGFkNzQxNTFiNzE1NzFjM2Y5NzJhMg==
  size: 14567286
resources/github-release-resource.tar.gz:
  object_id: b05b571e-9620-4e37-90f2-4a542782db8f
  sha: !binary |-
    YjM0ZjYyZDk5NTNkNzIzY2VjYTcxYmUyNmE1ZWJjMzMzYzcyM2E0Yg==
  size: 10119975
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: be0933a0-c0be-4ac7-a59c-bae77fa16705
  sha: !binary |-
    Y2I3Y2E3YThkYWE0OGZkYTFkYTVlYjYxMmZkMTRkNGY4NGMxMjUyOA==
  size: 8779768
resources/bosh-io-release-resource.tar.gz:
  object_id: 0d643139-9758-447c-a361-818bcc4d7e66
  sha: !binary |-
    NTQyMWUyNzE2OGI2MmVjMzk3ZWYzOWQ1MTNiNzhmN2JhOWQ2YjNhOA==
  size: 8778866
resources/bosh-deployment-resource.tar.gz:
  object_id: 7f8fbed9-8429-4e0e-b394-ecde3450bbf0
  sha: !binary |-
    YTA1NGFhYTczY2VmM2EzYzJlOWZjNzllYzM1OTZhYWE3NmI3YzVlYg==
  size: 22394143
btrfs_tools_3.12/btrfs:
  object_id: 8a522cff-b202-43a6-8d10-7e68c473f66e
  sha: 5d7afc7cff4e2d842dcc22129799b1329ed2e868
  size: 353424
btrfs_tools_3.12/mkfs.btrfs:
  object_id: 25651d29-52e3-4441-afc0-b590ea64c410
  sha: 80108e80d404d8fdd435703f8526ff8a44e4bbe2
  size: 171728
resources/pool-resource.tar.gz:
  object_id: b49136bf-e4a6-4a70-908a-e4747bb7ef37
  sha: 519d9b3dd2a48e551a1eb27ff871791fcfc6e2ae
  size: 9611452
golang_1.5/go1.5.1.linux-amd64.tar.gz:
  object_id: 6fe7cb89-c844-4191-a791-01a1625526ab
  sha: 46eecd290d8803887dec718c691cc243f2175fe0
  size: 77875767
