---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: a8512521-fe60-4730-827c-fbf30e16097f
  sha: !binary |-
    MzMzOGFjNjU4NzA1ZDU4ZDg2OGMxOTc4MzdiNTRiOGUyYmQ0ZWRjOA==
  size: 10016351
resources/time-resource.tar.gz:
  object_id: 4fe778c5-d7d7-4954-bffa-47da951490ad
  sha: !binary |-
    M2QxNzU5M2E4NmVlM2VlNmFlMmRiMGI5YmE2NWNkNGQzMGY2MTM2OQ==
  size: 2612659
resources/semver-resource.tar.gz:
  object_id: 693ff164-b24d-4a09-87a5-e581adb45851
  sha: !binary |-
    ZjI0YWM0ZjQ1ZWYwNzA5Y2I5MzRkODVjYWZmYzVjODUxYjlmYzA0Mg==
  size: 8903462
resources/s3-resource.tar.gz:
  object_id: c7e63f48-57bc-4461-9486-ca1b705a444f
  sha: !binary |-
    ZjQxOGQyMmI3YjdmZTEzY2FhOWIwYWM5YjZhMjdkZDVjMzNlOTFjMw==
  size: 9735691
resources/tracker-resource.tar.gz:
  object_id: 4f7df145-32ef-45d7-bc4a-ac4bfc346cc1
  sha: !binary |-
    ODExZjIzZDMxNmMyOWM3YWVkZThkZDM2ODI4ZTNhNWZiZGJhZTRhMA==
  size: 12031078
resources/git-resource.tar.gz:
  object_id: a6394fa3-cb75-4626-b9cc-7f333703e16a
  sha: !binary |-
    YmNmMTExMmM3MzNiNTNlMjQ5ZGM2ZmUzNGRhN2IwZmFiNmFlMTY1ZA==
  size: 8779619
resources/docker-image-resource.tar.gz:
  object_id: 1e1b9153-5003-44bb-a321-f11b6036d1f4
  sha: !binary |-
    ZjY0N2U5NzU5ZDEzMTgyYmI0YWRlZTg0NzEwNzJmZTdiODgyNjM0NQ==
  size: 10041262
resources/vagrant-cloud-resource.tar.gz:
  object_id: 412eba8e-1a4d-4e41-8ab9-27bec711830b
  sha: !binary |-
    OTlhZWFmNGNjZjM5Njg3MTNjMzhhMWJjNTcwODFmNjhhNjMzMTU3NA==
  size: 8423639
resources/cf-resource.tar.gz:
  object_id: 991ff01f-7e25-486b-99b2-38364af94327
  sha: !binary |-
    OWUzMzQwMWJmZTM1ZTRkMzNkZDg0YTVmZGY0Yjk3OWU5ZDI3OWE0NA==
  size: 14589107
resources/github-release-resource.tar.gz:
  object_id: e5ca6c9c-7361-4d5e-9cce-ef97ca4b5d1d
  sha: !binary |-
    Zjk5OTM5ODdkNDAxNzcwM2M2ZjE0OTY4OWJmY2M4YjdlNDViNmIwYw==
  size: 9147708
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 11c1ea0c-e6d9-48d5-809f-aac2913958ea
  sha: !binary |-
    ZGViY2M4MWQwNTBlYzY2ZTk0OTBkMjEzNWJkMWZkNzY4NTE5ZGJkZA==
  size: 8779462
resources/bosh-io-release-resource.tar.gz:
  object_id: 19874ea5-382c-449e-939a-5dcb5c8143ff
  sha: !binary |-
    MWVmNTBiNzUzZDkwZDNiNDE5MTYyNDA3NTZhYTcxYjkzYjIxMzBjYQ==
  size: 8778930
resources/bosh-deployment-resource.tar.gz:
  object_id: 48732533-71c9-4f65-a79e-436782cf3317
  sha: !binary |-
    MTE5YjEwYTQ5Nzg4NjQ4N2E0N2Q3YjcxZWZjNjAyNTk0NjgzYjljOQ==
  size: 22360800
btrfs_tools_3.12/btrfs:
  object_id: 8a522cff-b202-43a6-8d10-7e68c473f66e
  sha: 5d7afc7cff4e2d842dcc22129799b1329ed2e868
  size: 353424
btrfs_tools_3.12/mkfs.btrfs:
  object_id: 25651d29-52e3-4441-afc0-b590ea64c410
  sha: 80108e80d404d8fdd435703f8526ff8a44e4bbe2
  size: 171728
resources/pool-resource.tar.gz:
  object_id: c19d5b5a-4288-4e9f-80b9-f1fe9ff31184
  sha: !binary |-
    OGM2ZjU0YTE1ZTUwZWEyMjAwOWZkNmYyMGZhYTRiYjQxOGFkN2VkYQ==
  size: 9613423
