---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: b91d7f4c-701f-4ed2-bb6f-60cf25d2bc71
  sha: !binary |-
    OWE5Zjk5MzMxYmI0Y2ZhNTE4YmQ3OTNiMDM4MWVlZDVkYmYwMjMwZQ==
  size: 2549730
resources/time-resource.tar.gz:
  object_id: 1e6e46c8-3323-4fd0-a611-f4ee96d815b6
  sha: !binary |-
    NzdkZTNkODBhMWYwOGY3ODcxNTVmZjhkYzJkODhlMzI5ZTAzYjVkNA==
  size: 2518571
resources/semver-resource.tar.gz:
  object_id: 0c4d10a1-6ed2-4bcb-970a-684a8078530c
  sha: !binary |-
    MGVkMWY4MTAxMDk4ODU0Mjg2NDdkNWI1ZGEyMzdiNDJlZmZlM2ZkZg==
  size: 8626835
resources/s3-resource.tar.gz:
  object_id: 6d05f2e2-0243-4aaf-9008-7cd499f0c587
  sha: !binary |-
    NzZlMjZhOWNhMGUwMTIyODNlYzkwODE4NzcxM2RkMGJlMjViOTA0Yg==
  size: 8830296
resources/tracker-resource.tar.gz:
  object_id: 84e7eae3-67aa-4fcb-95df-0dc4cd6ac0d1
  sha: !binary |-
    NjZiNDVjODg4Nzk1ZjgxZjMwNTU2ZmZjOTZlYjhlNzZiMDU2ZDdlNg==
  size: 11534976
resources/git-resource.tar.gz:
  object_id: a00d1b35-d02a-4a9d-9f6c-9c6ec02cfca4
  sha: !binary |-
    YWJkNDVjNjllOWRiMTMyMmEwMjY3ZWI0MDZmNWMyMDE0NzBmMjg3OQ==
  size: 9155185
resources/docker-image-resource.tar.gz:
  object_id: f927a94b-d1b8-43a1-9037-72fef27f565b
  sha: !binary |-
    YmNmMDg0MWJjMTdiMzg1NGM4YTQ5N2IxNGI2YjAyODhmYmY1YTBiZA==
  size: 8069465
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: 36d7ba1a-08c3-4cc9-9f7e-ea844119dbaf
  sha: !binary |-
    YTc1ZGEyMTZkMjQzNjQ0OTczMjIzYWI3OGQyZTcyNGVkMzE4MmY3Mg==
  size: 9154774
resources/cf-resource.tar.gz:
  object_id: db0fc473-e518-43e7-98ac-863dbe1b080e
  sha: !binary |-
    YjQwMGI2NWViNjE2NzYxOGNjMGNkNzIyMzRiNjViMmVhNDBjODA0OQ==
  size: 12548251
