---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: !binary |-
    YjZiMTU0OTMzMDM5OTg3MDU2YWMzMDdlMjBjMjVmYTUwOGEwNmJhNg==
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: !binary |-
    OWY4MGIzY2ZlYmM0MzRjYTA4NjBmYzg0ODk5MjNjZWE3MzQ1NjA4MQ==
  size: 21865589
consul_0.3/consul:
  object_id: 03a93976-87ff-4d84-92b9-b03e0f979720
  sha: !binary |-
    NDhiOWI2NzFmNzU0NzliZWJjZTczOGYzMDY1NGUxODUyMGQ5NGM5Ng==
  size: 14388499
resources/archive-resource.tar.gz:
  object_id: 4c5f92b7-eb1f-47ef-b1f4-5a99b44a89e6
  sha: !binary |-
    N2VjYjU1ZTZhNzg2ZjkyZDVkY2JmYzMwNTg4NmU5MDVjMTA2NGExMg==
  size: 2549658
