---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: b91d7f4c-701f-4ed2-bb6f-60cf25d2bc71
  sha: !binary |-
    OWE5Zjk5MzMxYmI0Y2ZhNTE4YmQ3OTNiMDM4MWVlZDVkYmYwMjMwZQ==
  size: 2549730
resources/time-resource.tar.gz:
  object_id: 7ff8a7a3-d488-4622-9940-dee4a9f7e279
  sha: !binary |-
    ZjA5NTc4NzYzMTdlYTE4MDZkYmMxNWVlZmIzM2U4OGZhYWUwODY0Mw==
  size: 2518561
resources/semver-resource.tar.gz:
  object_id: 23250d86-0b38-4af6-a2e0-5bf504e2d57e
  sha: !binary |-
    ZjY1NzhmNWY3M2Y2ZWE2NDI0MWQxOWViNDBjM2I4ZDM5MWY2OTg1ZQ==
  size: 8618181
resources/s3-resource.tar.gz:
  object_id: 0ee4daba-f878-4b75-921a-95bb7c9bb988
  sha: !binary |-
    YTVlYjA4YTFhNTk4ZDk1ZGVjOWYzNzE2ZmM4MjVhZDVlMTdkOTFiMw==
  size: 8830227
resources/tracker-resource.tar.gz:
  object_id: 088f91f8-97b6-432e-ad89-1da31786acc9
  sha: !binary |-
    YzMzM2ZiZjY4MTQ2ZmJiZDc5NjJhODU1NjZiZjE3ZWMyMGZmOGQxNQ==
  size: 11537364
resources/git-resource.tar.gz:
  object_id: afb0b626-3b32-4787-9f49-46863b14b6b3
  sha: !binary |-
    M2JlZWE5MGNiYjExOGJiMWI3OTNmMWE2M2U4YjU1MTI1N2U1NjdlMQ==
  size: 9155168
resources/docker-image-resource.tar.gz:
  object_id: 968d64ba-de6b-4664-8356-89ebad347b97
  sha: !binary |-
    YjExMjc2MDA1MmVhOWExNDY3MTA1YzQ1YmMxZTEzY2NmZjg2ZDhlYg==
  size: 8277138
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: e3f29890-33a5-4768-af55-d6847537b39f
  sha: !binary |-
    YzIwYzNhODgzYmE4MjI3OGNmMTAxYzg3ODEyYTRiOGQ3ZjhlYzFmNg==
  size: 9154791
resources/cf-resource.tar.gz:
  object_id: 237c7717-638f-4bd5-98c1-ca910d3b0ef5
  sha: !binary |-
    NjE1YjgwZGY5M2Q4MTQxZTU4ZjVlOTI4ZjE4ZjViNDY3ZDZiZTVmZQ==
  size: 12629131
resources/github-release-resource.tar.gz:
  object_id: c292f3df-9bec-4c6c-92c0-f4ff7c62ae9a
  sha: !binary |-
    YWU1Y2MzYTRkYjFmMjBkNDViMmMwNzcwMjA4MTgxZTY2YjI2ZjA2Yg==
  size: 6776962
