---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: c3ccf92b-bb6b-4fe9-b1c8-3761c7118ba2
  sha: !binary |-
    MjNlN2NiY2I4ZjkzNTliMWI3ZmE4NDlmNTBmNGNhYmQ4OTBmMDBiMg==
  size: 2549624
resources/time-resource.tar.gz:
  object_id: 0096f331-17f4-4b73-88b3-af1a5df15b76
  sha: !binary |-
    MWU5ZjY1MTgwZjRkZWE3NWI1YjdhMWQ0MTNmZjYwZWUzOTA3OTI5ZA==
  size: 2518572
resources/semver-resource.tar.gz:
  object_id: 50b33e18-5d5a-4f5d-ab2c-456ca1ca764f
  sha: !binary |-
    MDQwYjMxMzM3NzcxNTc1M2RlODg1NTYzNGQ3NzY1OTFkOWZiMDg1Nw==
  size: 8619006
resources/s3-resource.tar.gz:
  object_id: 30689753-05a8-4aec-ae0a-7c33403c2343
  sha: !binary |-
    MmNjYThlOWNkMTE2YmJkM2I5OTBhYmFmYjY2YmE5ZDMzMjJmYWNhOQ==
  size: 8840017
resources/tracker-resource.tar.gz:
  object_id: 9ad7a288-6a9d-4476-8032-7e1333e23fa4
  sha: !binary |-
    YjFjYjM3NmNhNjY3MjU1YjdlMDlkOThjZTgzMjgwMWY3YzNjNWFiNA==
  size: 9882086
resources/git-resource.tar.gz:
  object_id: 73f35aa4-07ce-4aaf-9f9a-3bf24ef7c419
  sha: !binary |-
    NjQ0ZmZlMmU5MzcyMjMwMmNkYmI3NjY3NTMxMDk3OTI0YjA4NjRiOQ==
  size: 8411111
resources/docker-image-resource.tar.gz:
  object_id: b3f1c818-7e9a-4a34-b527-38deb66b6f5c
  sha: !binary |-
    NzFkODlkNmM5NzQ0ODg3ZDM0NWMzN2I1NWNjN2I2N2Y2Nzk1YWEzZQ==
  size: 8277135
resources/vagrant-cloud-resource.tar.gz:
  object_id: ba9762cd-b2bd-4f55-b610-2e2bb87f6f6d
  sha: !binary |-
    ODhlMDg2OTRhNzkzMzkxMDg0ZTdlZjA5MTBiZGNmZjRjYjllZDM0Yw==
  size: 8409175
resources/cf-resource.tar.gz:
  object_id: e7d1f1dd-2fde-4070-85d6-2a4474e37eac
  sha: !binary |-
    NWJhNWE1NGE5MDM2NjExOWFhNWY4MDdjNjk2ZDA0NGY4ZDc3ZTBkZA==
  size: 12679305
resources/github-release-resource.tar.gz:
  object_id: 2668e4bd-47ed-451c-8208-6a7256ab464a
  sha: !binary |-
    YWQxNmZiOTg0ZmU3N2FjMDc2ZGNkMTAyYzkxZGM1NzE1MDMxZGViYw==
  size: 8832803
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 1c0565d1-346a-4d00-b5fa-cc2ee5f5507d
  sha: !binary |-
    N2M0MjFjODdhYjY4ZDE0NjVhZDZjY2I3Y2FhOTlkNTc1NTVkNmUyZQ==
  size: 8407982
resources/bosh-io-release-resource.tar.gz:
  object_id: aa5ccb8f-02be-4ff3-aa52-393125388c17
  sha: !binary |-
    ZDk5ZDAxYjg1NGZlZTNkODdjZTcyNTkyMzNjYWMzOTBjZjk0NjExOQ==
  size: 8409049
