---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: b91d7f4c-701f-4ed2-bb6f-60cf25d2bc71
  sha: !binary |-
    OWE5Zjk5MzMxYmI0Y2ZhNTE4YmQ3OTNiMDM4MWVlZDVkYmYwMjMwZQ==
  size: 2549730
resources/time-resource.tar.gz:
  object_id: e763b9f2-17df-4da4-8def-e971da8e82f8
  sha: !binary |-
    NjVjNmNhOGUwYjUzOWZiMGZmMDQ4NzQ0YTIwNDJhNzBhNDNkZjUzYg==
  size: 2518565
resources/semver-resource.tar.gz:
  object_id: a290ea61-c977-42c6-98ff-54bf21b642c6
  sha: !binary |-
    YWEyNzZiNDZkNDMwNWI3MGNhZjQyNTE3MWRlMzM5NTEzYmUwYjg3Mw==
  size: 8618168
resources/s3-resource.tar.gz:
  object_id: c4815e46-7138-4f7f-a0ad-8b5c54508492
  sha: !binary |-
    ZWUyYmMxMjkzMjUwZWNkYTQ5MmQxOWM1ZDhkZTkwMDdjOGRiMTcwNA==
  size: 8830243
resources/tracker-resource.tar.gz:
  object_id: 088f91f8-97b6-432e-ad89-1da31786acc9
  sha: !binary |-
    YzMzM2ZiZjY4MTQ2ZmJiZDc5NjJhODU1NjZiZjE3ZWMyMGZmOGQxNQ==
  size: 11537364
resources/git-resource.tar.gz:
  object_id: afb0b626-3b32-4787-9f49-46863b14b6b3
  sha: !binary |-
    M2JlZWE5MGNiYjExOGJiMWI3OTNmMWE2M2U4YjU1MTI1N2U1NjdlMQ==
  size: 9155168
resources/docker-image-resource.tar.gz:
  object_id: cf4950e4-e1a2-42c7-9e76-a15e47b00eb5
  sha: !binary |-
    MTAxZmUzNmYzYmY2NmQ0MDVmNTM1NjY5Mjg3NWIwOWMyYTBmZGFjMw==
  size: 8069434
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: 0cfd7222-bd5f-4f7e-93ad-5a4d8dd827aa
  sha: !binary |-
    YjUwODdhZDEyMmNjMjFhOTQ5ZDY0Mjk2M2Y3ZGNmOTIwNGJmMmE5Nw==
  size: 9154707
resources/cf-resource.tar.gz:
  object_id: 237c7717-638f-4bd5-98c1-ca910d3b0ef5
  sha: !binary |-
    NjE1YjgwZGY5M2Q4MTQxZTU4ZjVlOTI4ZjE4ZjViNDY3ZDZiZTVmZQ==
  size: 12629131
resources/github-release-resource.tar.gz:
  object_id: 4345807c-141f-4be8-b353-6075b15307be
  sha: !binary |-
    ZTM4ODc2MTI5ODhmMmVjMmYyNjI0NThlY2U2NGEzMjk3NTFkNWZkNg==
  size: 6777072
