---
aufs/aufs-tools_20110410-1_amd64.deb:
  object_id: 79ed3b90-6be7-48fb-9d86-6d22a336d946
  sha: !binary |-
    NmYyMDIzMDhmNTc4ZGU3ZWE1NGZjMmRkMGI0NGI2NjY4MDRmOWJhNg==
  size: 98338
iptables/iptables-1.4.21.tar.bz2:
  object_id: 2bc7b7eb-d543-49f2-a8a7-6ac692ba4b0e
  sha: !binary |-
    ODVkNDE2MDUzNzU0NmEyM2E3ZTQyYmMyNmRkN2VlNjJhMGVkZTRjOA==
  size: 547439
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: !binary |-
    YjZiMTU0OTMzMDM5OTg3MDU2YWMzMDdlMjBjMjVmYTUwOGEwNmJhNg==
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: !binary |-
    OWY4MGIzY2ZlYmM0MzRjYTA4NjBmYzg0ODk5MjNjZWE3MzQ1NjA4MQ==
  size: 21865589
consul_0.3/consul:
  object_id: 03a93976-87ff-4d84-92b9-b03e0f979720
  sha: !binary |-
    NDhiOWI2NzFmNzU0NzliZWJjZTczOGYzMDY1NGUxODUyMGQ5NGM5Ng==
  size: 14388499
