---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: a8512521-fe60-4730-827c-fbf30e16097f
  sha: !binary |-
    MzMzOGFjNjU4NzA1ZDU4ZDg2OGMxOTc4MzdiNTRiOGUyYmQ0ZWRjOA==
  size: 10016351
resources/time-resource.tar.gz:
  object_id: f4560915-dffc-4438-8d0a-a91ee790f6ef
  sha: !binary |-
    Y2U1ODgwNzRmZmQyNjBhNTJiYjk5Nzc2YTg2NzkzYjcwZGE4YjdiMA==
  size: 2612667
resources/semver-resource.tar.gz:
  object_id: e43e605c-2aac-4ee2-835f-8429804a5d2e
  sha: !binary |-
    ZTMwMTk4M2RlMWMxNjFjYmRlMzI1ODlkNDZkNzhkOTY1ZWIyOWVjYg==
  size: 8954191
resources/s3-resource.tar.gz:
  object_id: 128c7f32-7df8-4c3f-801e-7e5ffe45d432
  sha: !binary |-
    ODk1YTMzYzEwM2E4MDdkZWVhOTRlOThlZDA1MDEwYjIzZDk3ZjQ4OQ==
  size: 9735616
resources/tracker-resource.tar.gz:
  object_id: 697d3fec-7fed-429c-b975-2bb4c0da2b0b
  sha: !binary |-
    ODRjYTJjOWFiNWFjMGE3ZjEyOTc1NmRmZmVmYzc1OWMyZDYzNjI2NQ==
  size: 12036506
resources/git-resource.tar.gz:
  object_id: 906b5d66-6ef9-4e91-bc36-d037d5d2e007
  sha: !binary |-
    OWFlZTY0MjU0MmQ1Yzc5NTc5MmJhYzRkNjMzMWQ2N2M2MDAyMTU2Zg==
  size: 8779834
resources/docker-image-resource.tar.gz:
  object_id: 97bb44a9-98d3-4b17-96d7-696ab5dbfbe9
  sha: !binary |-
    OWYwMTA1ODllM2ViOGQyOThlODJhMTcxZWIzMTU1NGJhODY0MzAwYg==
  size: 10041359
resources/vagrant-cloud-resource.tar.gz:
  object_id: 3c17d93c-fdb3-4716-9102-3a19a923e14c
  sha: !binary |-
    MGQ1MGU4Y2Q0Y2ZhZjliOTM3NTQzNDAyYTRiZjdjZDllZDY1YTNkNQ==
  size: 8778654
resources/cf-resource.tar.gz:
  object_id: c0dfa256-79f4-469b-90d2-c07c989fb144
  sha: !binary |-
    YTQ5Mjc5ZDViZjFlODFmYzI1ZDEzN2JkODZhMjkyOTI0ZTM5YTRhZA==
  size: 14522990
resources/github-release-resource.tar.gz:
  object_id: e437e16c-8ece-4c9b-b16c-4d11c14036b5
  sha: !binary |-
    OTE1MWEzZWI0ZjcwZDg4YmFmMTUxODRkMzk3MDBlZDE3NGY0ZTYwNw==
  size: 9183022
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: be0933a0-c0be-4ac7-a59c-bae77fa16705
  sha: !binary |-
    Y2I3Y2E3YThkYWE0OGZkYTFkYTVlYjYxMmZkMTRkNGY4NGMxMjUyOA==
  size: 8779768
resources/bosh-io-release-resource.tar.gz:
  object_id: 0d643139-9758-447c-a361-818bcc4d7e66
  sha: !binary |-
    NTQyMWUyNzE2OGI2MmVjMzk3ZWYzOWQ1MTNiNzhmN2JhOWQ2YjNhOA==
  size: 8778866
resources/bosh-deployment-resource.tar.gz:
  object_id: 7f8fbed9-8429-4e0e-b394-ecde3450bbf0
  sha: !binary |-
    YTA1NGFhYTczY2VmM2EzYzJlOWZjNzllYzM1OTZhYWE3NmI3YzVlYg==
  size: 22394143
btrfs_tools_3.12/btrfs:
  object_id: 8a522cff-b202-43a6-8d10-7e68c473f66e
  sha: 5d7afc7cff4e2d842dcc22129799b1329ed2e868
  size: 353424
btrfs_tools_3.12/mkfs.btrfs:
  object_id: 25651d29-52e3-4441-afc0-b590ea64c410
  sha: 80108e80d404d8fdd435703f8526ff8a44e4bbe2
  size: 171728
resources/pool-resource.tar.gz:
  object_id: 6ffb2ce5-ab59-4cdd-a621-e955e7e9891d
  sha: !binary |-
    MWZlZTVmMTE0MzJlOWY0YmRiMmZlZTU5NDM4ZmYwZTViODNmMmI4Mg==
  size: 9613456
