---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: 92348b2f-3f70-4c97-a7d2-eba498963e2b
  sha: !binary |-
    MDcwZTRmYzg2ZDY4MWVkODE1M2JjODUyNjhlZTU0OTcwZDEyNGUzZA==
  size: 10428189
resources/time-resource.tar.gz:
  object_id: 5a33446b-ba48-4ebe-9e8f-88f003c502e0
  sha: !binary |-
    NmUzN2YzZWY0NzY1MmYzMGE4NDcwYmI3NmRiN2JiOGNkMDFlMWQzMw==
  size: 2467425
resources/semver-resource.tar.gz:
  object_id: 848c1a9b-6be8-4804-82f2-af1e80d347c1
  sha: !binary |-
    MzlmMzlhNTE3YjRiZjhiZWQ0NTg2ODNkYjE1Njg3ZWM0YmI3NGVjZg==
  size: 14766551
resources/s3-resource.tar.gz:
  object_id: 2145d2c7-4d62-468d-9972-bfa96006824c
  sha: !binary |-
    ZmJhMWIxMmJkOTQ5MTc4MzI2OWM4NGExOTc1NDc2NGE2YTNhYjdmMw==
  size: 10998551
resources/tracker-resource.tar.gz:
  object_id: 66f1b4b3-20a1-49ac-85c5-a553096f33cb
  sha: !binary |-
    YzIxYjllZDVjMmM5ZTA3YjIyMzlkOWY5OWE4Y2QwNTExMGQ5MzIxMg==
  size: 12653722
resources/git-resource.tar.gz:
  object_id: b5048d20-d48a-419c-a5b2-2b2646add7c6
  sha: !binary |-
    ZWQzMmZkNDQ1ZThlNmJhNDdhOGYzNzFlN2U0ZWQ4MDA3N2Y4ZGRkYg==
  size: 8779812
resources/docker-image-resource.tar.gz:
  object_id: d00fb8da-86f9-4964-bfd0-0f0ff3acb636
  sha: !binary |-
    NGRhMWQwOGIyMzI4NTBhMzQ4ZTM5Zjc1YTI5ZmJkN2E1MGJjOGY3Nw==
  size: 10038422
resources/vagrant-cloud-resource.tar.gz:
  object_id: 3c17d93c-fdb3-4716-9102-3a19a923e14c
  sha: !binary |-
    MGQ1MGU4Y2Q0Y2ZhZjliOTM3NTQzNDAyYTRiZjdjZDllZDY1YTNkNQ==
  size: 8778654
resources/cf-resource.tar.gz:
  object_id: a3b2aee8-356d-4a13-a9b9-d2ce3346f004
  sha: !binary |-
    NjBkZWI2YjBlOTNjZTYwZTE0YjVkOGExN2Q0Y2QzNTVmYzg3MWUwZg==
  size: 16187357
resources/github-release-resource.tar.gz:
  object_id: 806e2c9b-d0dd-45e8-a086-66d16309def8
  sha: !binary |-
    MTlmYTc0ZTFlMzVlZDBjMzgwYjViZDZlM2NiZDdlMDIxZWVkYmZjZQ==
  size: 10125873
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: be0933a0-c0be-4ac7-a59c-bae77fa16705
  sha: !binary |-
    Y2I3Y2E3YThkYWE0OGZkYTFkYTVlYjYxMmZkMTRkNGY4NGMxMjUyOA==
  size: 8779768
resources/bosh-io-release-resource.tar.gz:
  object_id: 0d643139-9758-447c-a361-818bcc4d7e66
  sha: !binary |-
    NTQyMWUyNzE2OGI2MmVjMzk3ZWYzOWQ1MTNiNzhmN2JhOWQ2YjNhOA==
  size: 8778866
resources/bosh-deployment-resource.tar.gz:
  object_id: 1037bfd6-f9d6-4d58-b1ab-0b6d81cdf52c
  sha: !binary |-
    ZGZlZDc5ZGM0NDc1OWMwZTMzOTBhMTdlYWIxODQ3N2MxZTAxZjA2OQ==
  size: 22425932
btrfs_tools_3.12/btrfs:
  object_id: 8a522cff-b202-43a6-8d10-7e68c473f66e
  sha: 5d7afc7cff4e2d842dcc22129799b1329ed2e868
  size: 353424
btrfs_tools_3.12/mkfs.btrfs:
  object_id: 25651d29-52e3-4441-afc0-b590ea64c410
  sha: 80108e80d404d8fdd435703f8526ff8a44e4bbe2
  size: 171728
resources/pool-resource.tar.gz:
  object_id: 3ccc4148-30ee-486e-b314-cfd7014bd26b
  sha: !binary |-
    ZDUzZWFlNDRkYmZiYjIxN2RiOWE0ZGUxOGI1YjE1ZDU3NTllNTNlOA==
  size: 9611455
golang_1.5/go1.5.1.linux-amd64.tar.gz:
  object_id: 6fe7cb89-c844-4191-a791-01a1625526ab
  sha: 46eecd290d8803887dec718c691cc243f2175fe0
  size: 77875767
