---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: 54d8357f-5718-4b53-8101-87f91394468b
  sha: !binary |-
    ODRkNGZkOWU4M2RlMTNmNjBkYTBmMzBmMjI5YTQ3NDAxMWUyOGFjOQ==
  size: 2549518
resources/time-resource.tar.gz:
  object_id: d3b0e267-596e-4b24-bb91-8875517807b2
  sha: !binary |-
    OTUzZjQ5MGFjMTY4ODNlNjNhY2RiMGZmYTVhZjNjOWZhMzIwNzgyNg==
  size: 2518566
resources/semver-resource.tar.gz:
  object_id: 0c4d10a1-6ed2-4bcb-970a-684a8078530c
  sha: !binary |-
    MGVkMWY4MTAxMDk4ODU0Mjg2NDdkNWI1ZGEyMzdiNDJlZmZlM2ZkZg==
  size: 8626835
resources/s3-resource.tar.gz:
  object_id: 6d05f2e2-0243-4aaf-9008-7cd499f0c587
  sha: !binary |-
    NzZlMjZhOWNhMGUwMTIyODNlYzkwODE4NzcxM2RkMGJlMjViOTA0Yg==
  size: 8830296
resources/tracker-resource.tar.gz:
  object_id: f8c1d8d2-08d0-4442-b8ac-1c5bc347c96f
  sha: !binary |-
    ZTY4YmVlMjgwYzY4MDlkMzlhNjg4YjQ5ODZlNmY1NjdhMDA4ZGVkMA==
  size: 11532746
resources/git-resource.tar.gz:
  object_id: 71aa4863-f56e-44b7-a4f4-f78d33a6b404
  sha: !binary |-
    OTNiZGYwMmUzZGZhOWU3ZTNiNDM0NmJkOGU3M2U0ZWU3MWIxYzQ5Ng==
  size: 9155185
resources/docker-image-resource.tar.gz:
  object_id: 6728a154-dd67-45b8-9e50-a86a897694b7
  sha: !binary |-
    NzhmNDNmMjNkMzY4ZGMwODE1NmUyZTU1NTQ0OTNhNzJjODcwNmU1Zg==
  size: 7953829
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: 48590c46-1b66-48d5-a305-db3b5ac56519
  sha: !binary |-
    ZDAyZjU0OGFhMGYyMjcxNDMyZTExNzFjNGQ3MTIyNTRkMTMxYjYyYg==
  size: 9154745
resources/cf-resource.tar.gz:
  object_id: 05d8a778-8ebf-4856-ab1d-a02d293a492a
  sha: !binary |-
    YTgwZjU2ZWU1NGQ5OWYyZGQ4M2NkNzA2ZmQ2YjAwN2FlNTgxZTc1Ng==
  size: 12497563
