---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: c3ccf92b-bb6b-4fe9-b1c8-3761c7118ba2
  sha: !binary |-
    MjNlN2NiY2I4ZjkzNTliMWI3ZmE4NDlmNTBmNGNhYmQ4OTBmMDBiMg==
  size: 2549624
resources/time-resource.tar.gz:
  object_id: 1eab47f9-4697-49ed-81be-b4ceda1dfa9c
  sha: !binary |-
    ZTkwMzdhMmJiMTkyN2M5OTBiOWY2MmRmNTJiYTUxMTQ2ZmQxMWY3Nw==
  size: 2524048
resources/semver-resource.tar.gz:
  object_id: e0cddad7-0f75-4002-808d-5ca30017e322
  sha: !binary |-
    ZjlhYTg0NDRlMTU2Nzc4NTQ4OWM2ZGZjNjM0MmVmMTVjODgwY2U5MA==
  size: 8644996
resources/s3-resource.tar.gz:
  object_id: 751e7f39-9399-41b8-a1d4-e9a99f263180
  sha: !binary |-
    NjJkOGU1ZmRkZmU3MTVhMDQ0NmZiNzBlMDk1ZDg4OWQyN2M2MDdmMA==
  size: 8839800
resources/tracker-resource.tar.gz:
  object_id: 9ad7a288-6a9d-4476-8032-7e1333e23fa4
  sha: !binary |-
    YjFjYjM3NmNhNjY3MjU1YjdlMDlkOThjZTgzMjgwMWY3YzNjNWFiNA==
  size: 9882086
resources/git-resource.tar.gz:
  object_id: 8ad3ec72-1226-48f6-b57c-9b6c8d65486b
  sha: !binary |-
    ZTAwNWIxYzNkNTA3MTU0Mzg3MjBlMTc5YTYwNGRlZTE2MmYwODRmNw==
  size: 8411400
resources/docker-image-resource.tar.gz:
  object_id: 271c8bbc-e6cd-409d-b587-bbc9b488b687
  sha: !binary |-
    MDc4MzFhOTNiNjk4NzZmNTNkNWQ2ZjhiMGJiZDIyYzI1ZDkzMzIxOA==
  size: 8388850
resources/vagrant-cloud-resource.tar.gz:
  object_id: 7a929a84-d9bf-48a9-8116-0f5f09ef4139
  sha: !binary |-
    OGNjZTZiOGU3NzJhNWU4MGYyNTExOTMwNDMwOWQ2Yzc3ZTBjYjg0NA==
  size: 8409188
resources/cf-resource.tar.gz:
  object_id: 96703eb8-6bd8-4108-a9a9-d3fbdfd37324
  sha: !binary |-
    MGYyN2QzNzdiMjkwMTdlMTM4MTg2M2EyMGJmMTg0NjJiYmUxZDYyZQ==
  size: 12731951
resources/github-release-resource.tar.gz:
  object_id: 704f07cb-2425-41ed-bb7f-c0d7402d5a04
  sha: !binary |-
    YmNjMWQxZmI4NWQwM2RjNTI3ZGQ1M2ZlMDQ5NWVhODlmNzBmOWRkNg==
  size: 8841286
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 6709e19c-369b-4d0d-bf25-f7d655024c9f
  sha: !binary |-
    Y2E0OGFlMmRlM2EzYTQ2YzU4N2ZjNWNhZGYzYWY4Yzc1NGMyYzI0OA==
  size: 8407988
resources/bosh-io-release-resource.tar.gz:
  object_id: 8b247e46-8f37-4656-bda8-9fd65d05df98
  sha: !binary |-
    OTcyNThjMzAzOTVlMGQ4Y2YxYTdkMzZhNzE1MjMwZDBhZTg0MDVjYQ==
  size: 8409411
resources/bosh-deployment-resource.tar.gz:
  object_id: 0f5386c7-d0fe-41e0-b2e8-babe5af7f76a
  sha: !binary |-
    YTliZDA3MzA3NWI5Y2Y1MzkyM2U2OWI1OWM5ZjIzZTBiYWVmNTk1ZQ==
  size: 22125992
