---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: 0d1c3a7c-7a35-490a-b7ba-c33070e7299a
  sha: !binary |-
    M2VjMTVmN2E2ODBjMGM1MGEzOTFmZTBlZWY2MGMwNDQ3MjlmMjYzNw==
  size: 11402362
resources/time-resource.tar.gz:
  object_id: 5a33446b-ba48-4ebe-9e8f-88f003c502e0
  sha: !binary |-
    NmUzN2YzZWY0NzY1MmYzMGE4NDcwYmI3NmRiN2JiOGNkMDFlMWQzMw==
  size: 2467425
resources/semver-resource.tar.gz:
  object_id: 848c1a9b-6be8-4804-82f2-af1e80d347c1
  sha: !binary |-
    MzlmMzlhNTE3YjRiZjhiZWQ0NTg2ODNkYjE1Njg3ZWM0YmI3NGVjZg==
  size: 14766551
resources/s3-resource.tar.gz:
  object_id: 8b858b7f-fae4-446e-a6ea-cc25a2fe43ef
  sha: !binary |-
    OTc4MDg2MWZhYWNmZDBiZDg0OGUzOWU0N2VhY2Y1Y2JhNGRjMDQ0NA==
  size: 11470168
resources/tracker-resource.tar.gz:
  object_id: 66f1b4b3-20a1-49ac-85c5-a553096f33cb
  sha: !binary |-
    YzIxYjllZDVjMmM5ZTA3YjIyMzlkOWY5OWE4Y2QwNTExMGQ5MzIxMg==
  size: 12653722
resources/git-resource.tar.gz:
  object_id: 7ad657bf-de99-4e71-8ca9-50acb00f5f5b
  sha: !binary |-
    YTE3NzM0ZDBmMTgyMWRkYmRkMTFjZWMxMjA5N2MwYWIwYzg3ZjdiNg==
  size: 8779773
resources/docker-image-resource.tar.gz:
  object_id: d00fb8da-86f9-4964-bfd0-0f0ff3acb636
  sha: !binary |-
    NGRhMWQwOGIyMzI4NTBhMzQ4ZTM5Zjc1YTI5ZmJkN2E1MGJjOGY3Nw==
  size: 10038422
resources/vagrant-cloud-resource.tar.gz:
  object_id: 3c17d93c-fdb3-4716-9102-3a19a923e14c
  sha: !binary |-
    MGQ1MGU4Y2Q0Y2ZhZjliOTM3NTQzNDAyYTRiZjdjZDllZDY1YTNkNQ==
  size: 8778654
resources/cf-resource.tar.gz:
  object_id: 61fdab64-cb1c-45de-bd21-80ea12436989
  sha: !binary |-
    MzJhZTBlZmRlNGQ3MzFkNDdkYTExOTIwNmZkMzE0YmM3MGIwM2JhMQ==
  size: 16187656
resources/github-release-resource.tar.gz:
  object_id: 22516307-3d29-4f1e-ab04-057d9d1f64ee
  sha: !binary |-
    NTRlMTQ3YzcyNzMzNWZjM2FlNTBhYTdkM2I0MjBkOGJlNzA4NjJmMw==
  size: 10167457
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: edfd0252-67d5-4783-9c7d-689b09989d4e
  sha: !binary |-
    ODA4MDdiZGIwZDI3Mzk3NDY5MTMzM2I1ZDUzODA4YTgwMGZjOWQ2Ng==
  size: 8777481
resources/bosh-io-release-resource.tar.gz:
  object_id: 0d643139-9758-447c-a361-818bcc4d7e66
  sha: !binary |-
    NTQyMWUyNzE2OGI2MmVjMzk3ZWYzOWQ1MTNiNzhmN2JhOWQ2YjNhOA==
  size: 8778866
resources/bosh-deployment-resource.tar.gz:
  object_id: 1037bfd6-f9d6-4d58-b1ab-0b6d81cdf52c
  sha: !binary |-
    ZGZlZDc5ZGM0NDc1OWMwZTMzOTBhMTdlYWIxODQ3N2MxZTAxZjA2OQ==
  size: 22425932
btrfs_tools_3.12/btrfs:
  object_id: 8a522cff-b202-43a6-8d10-7e68c473f66e
  sha: 5d7afc7cff4e2d842dcc22129799b1329ed2e868
  size: 353424
btrfs_tools_3.12/mkfs.btrfs:
  object_id: 25651d29-52e3-4441-afc0-b590ea64c410
  sha: 80108e80d404d8fdd435703f8526ff8a44e4bbe2
  size: 171728
resources/pool-resource.tar.gz:
  object_id: a4959967-fb0c-4bee-a7e5-b3d4d2145f71
  sha: !binary |-
    NWRjZGQwMmQzZDQxMGMzNTQ1MmM1OTZiOWVhYzVlMWQwNDQyNTJlMQ==
  size: 9614492
golang_1.5/go1.5.1.linux-amd64.tar.gz:
  object_id: 6fe7cb89-c844-4191-a791-01a1625526ab
  sha: 46eecd290d8803887dec718c691cc243f2175fe0
  size: 77875767
