---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: !binary |-
    YjZiMTU0OTMzMDM5OTg3MDU2YWMzMDdlMjBjMjVmYTUwOGEwNmJhNg==
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: !binary |-
    OWY4MGIzY2ZlYmM0MzRjYTA4NjBmYzg0ODk5MjNjZWE3MzQ1NjA4MQ==
  size: 21865589
consul_0.3/consul:
  object_id: 03a93976-87ff-4d84-92b9-b03e0f979720
  sha: !binary |-
    NDhiOWI2NzFmNzU0NzliZWJjZTczOGYzMDY1NGUxODUyMGQ5NGM5Ng==
  size: 14388499
resources/archive-resource.tar.gz:
  object_id: d0af336c-9c75-4dff-8a23-46082a0ba17d
  sha: !binary |-
    M2Q5M2NiMWI1MmVkZmQ1ZWQ0YWRkODdjNDFkZDgxNWI2NmU5OTI1MA==
  size: 2549739
resources/time-resource.tar.gz:
  object_id: bde75726-a401-4c65-90ca-95d8d49e72f2
  sha: !binary |-
    NGMwNDE5NjM2ZTJjYmI5ZTIwNGFlNjQ5ZDQ0NzYxYjBkZWM0MDRmNA==
  size: 2518571
resources/semver-resource.tar.gz:
  object_id: 7052d2d7-c678-40a6-83f7-b9019f630ba4
  sha: !binary |-
    NWU3MWYyMDlkNDJhZGQ2ZTcwZDgwN2QwMWExNmExYjc1ZmY4MWIyZQ==
  size: 8606963
resources/s3-resource.tar.gz:
  object_id: a862ec64-9dcd-4c17-a833-31ca7c45dbc4
  sha: !binary |-
    M2FjZWFjODFiOTE1ZmM1NDc4MWExZTE0NGRhZjg1ZGZiODkxMDE2Yw==
  size: 8807415
resources/tracker-resource.tar.gz:
  object_id: 144133a1-3eed-4a48-8915-406b180bf44c
  sha: !binary |-
    ZWEyMDMzOTNhNTVmNjQ0MGMyZmQyYWZlMDkxYmE5NGY5Mjk1ZWNkMQ==
  size: 5085070
