---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: c3ccf92b-bb6b-4fe9-b1c8-3761c7118ba2
  sha: !binary |-
    MjNlN2NiY2I4ZjkzNTliMWI3ZmE4NDlmNTBmNGNhYmQ4OTBmMDBiMg==
  size: 2549624
resources/time-resource.tar.gz:
  object_id: 1eab47f9-4697-49ed-81be-b4ceda1dfa9c
  sha: !binary |-
    ZTkwMzdhMmJiMTkyN2M5OTBiOWY2MmRmNTJiYTUxMTQ2ZmQxMWY3Nw==
  size: 2524048
resources/semver-resource.tar.gz:
  object_id: e0cddad7-0f75-4002-808d-5ca30017e322
  sha: !binary |-
    ZjlhYTg0NDRlMTU2Nzc4NTQ4OWM2ZGZjNjM0MmVmMTVjODgwY2U5MA==
  size: 8644996
resources/s3-resource.tar.gz:
  object_id: 751e7f39-9399-41b8-a1d4-e9a99f263180
  sha: !binary |-
    NjJkOGU1ZmRkZmU3MTVhMDQ0NmZiNzBlMDk1ZDg4OWQyN2M2MDdmMA==
  size: 8839800
resources/tracker-resource.tar.gz:
  object_id: 9ad7a288-6a9d-4476-8032-7e1333e23fa4
  sha: !binary |-
    YjFjYjM3NmNhNjY3MjU1YjdlMDlkOThjZTgzMjgwMWY3YzNjNWFiNA==
  size: 9882086
resources/git-resource.tar.gz:
  object_id: 3cd44e0e-ea84-47e2-9738-aa450f708b72
  sha: !binary |-
    NDIzMDZiYWFjNTM4OTM4MDZhMzI3ZTAwMWY2YmFmM2VkMDNmMDA0Yw==
  size: 8411402
resources/docker-image-resource.tar.gz:
  object_id: b3f1c818-7e9a-4a34-b527-38deb66b6f5c
  sha: !binary |-
    NzFkODlkNmM5NzQ0ODg3ZDM0NWMzN2I1NWNjN2I2N2Y2Nzk1YWEzZQ==
  size: 8277135
resources/vagrant-cloud-resource.tar.gz:
  object_id: ba9762cd-b2bd-4f55-b610-2e2bb87f6f6d
  sha: !binary |-
    ODhlMDg2OTRhNzkzMzkxMDg0ZTdlZjA5MTBiZGNmZjRjYjllZDM0Yw==
  size: 8409175
resources/cf-resource.tar.gz:
  object_id: bb3bb8c2-b3ca-41e7-9542-8d451e56c982
  sha: !binary |-
    YjAxOWIyNzY3ZDlkOTE3NGFhYmE1NDRhZTY2MjY1OGJlODlhMTlkOA==
  size: 12738037
resources/github-release-resource.tar.gz:
  object_id: bac6b719-74d5-44b4-a40f-237f6bff5022
  sha: !binary |-
    NzhiOTg2ZDE1OWMyYmEyNWEyOGQ4NGM3NWQxYWIwZGFkOTdlMDIzYw==
  size: 8841271
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 215c153d-3505-48e1-aa01-dfcfc34130f8
  sha: !binary |-
    ZDUwMjEzYTU0Nzc4YmM1ODA3MDUyZGRjOTAyOTU5MTU5NDgyMjEyNQ==
  size: 8407356
resources/bosh-io-release-resource.tar.gz:
  object_id: 2b39e0a1-bbc8-4d59-8bd0-1eb6e1d6186f
  sha: !binary |-
    ZmY4Y2JlZDQwZjc3NmNiZTg5ZmZlMzNmZDRjNDk0Y2UyY2ViOWVhYQ==
  size: 8407390
resources/bosh-deployment-resource.tar.gz:
  object_id: 0f5386c7-d0fe-41e0-b2e8-babe5af7f76a
  sha: !binary |-
    YTliZDA3MzA3NWI5Y2Y1MzkyM2U2OWI1OWM5ZjIzZTBiYWVmNTk1ZQ==
  size: 22125992
