---
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: a9d03488-fe6c-44c6-a815-d0b76d7afe17
  sha: !binary |-
    MGRlODkyZmM3MzYxZjM2MmFkN2U4NDFmY2E4NTQyZmNmYTA3ODVkMA==
  size: 9647998
resources/time-resource.tar.gz:
  object_id: 860dd863-312c-4a31-8db3-a26f4d92edea
  sha: !binary |-
    NjgwN2QyMjI3ZTJjZmE1MWVjNjFiYWNmMmU3ZDZhN2Q4MzMzNDU1YQ==
  size: 2524039
resources/semver-resource.tar.gz:
  object_id: 0f97571b-3fa9-4c58-b519-497e516f489e
  sha: !binary |-
    ZTlkM2Q4ZGRlYjUxMjU2MGQ3MjBhYjdlNTM0ZjM0NzdmODE3MTM0Nw==
  size: 8644983
resources/s3-resource.tar.gz:
  object_id: a0bfdb0e-fa0e-49b1-8c21-e66a43ae9081
  sha: !binary |-
    ZDI4YjEyZTM2YjY2YWQ3YzdhMzliZTdmZmQzNWY2ZGU2ZGQ3MjEzYQ==
  size: 8839928
resources/tracker-resource.tar.gz:
  object_id: 747605a7-1729-4a54-b5c3-6afb8189ccc1
  sha: !binary |-
    NGM3N2JmYjc4ZWQzMGQ1MzE4M2U1ODdkY2I4MTNjYzIwODhiYTNjZg==
  size: 10800985
resources/git-resource.tar.gz:
  object_id: ce133b61-f1a3-4c29-ab0a-251f51ec4453
  sha: !binary |-
    YjczOWY3MzZlNWI3MzFmYTI1NWM5ZTU2Y2E5YTljODZmNWIyM2EzNw==
  size: 8410518
resources/docker-image-resource.tar.gz:
  object_id: 271c8bbc-e6cd-409d-b587-bbc9b488b687
  sha: !binary |-
    MDc4MzFhOTNiNjk4NzZmNTNkNWQ2ZjhiMGJiZDIyYzI1ZDkzMzIxOA==
  size: 8388850
resources/vagrant-cloud-resource.tar.gz:
  object_id: 7a929a84-d9bf-48a9-8116-0f5f09ef4139
  sha: !binary |-
    OGNjZTZiOGU3NzJhNWU4MGYyNTExOTMwNDMwOWQ2Yzc3ZTBjYjg0NA==
  size: 8409188
resources/cf-resource.tar.gz:
  object_id: b82fe315-57cc-4620-9598-716539000626
  sha: !binary |-
    YTM0ZGE3YjYyZWVmNmU0M2VkZGYyYzRkZWVjOGI3MTQyNmVkMWMwYg==
  size: 12731742
resources/github-release-resource.tar.gz:
  object_id: 704f07cb-2425-41ed-bb7f-c0d7402d5a04
  sha: !binary |-
    YmNjMWQxZmI4NWQwM2RjNTI3ZGQ1M2ZlMDQ5NWVhODlmNzBmOWRkNg==
  size: 8841286
consul_0.5/consul:
  object_id: 97b99488-7553-47f0-8294-ad1f8533b164
  sha: f461a632165ce878045afaaf04de699510e53374
  size: 17734417
golang_1.4/go1.4.2.src.tar.gz:
  object_id: 774af869-61a5-47ec-955c-41b00a96e941
  sha: 460caac03379f746c473814a65223397e9c9a2f6
  size: 10921896
resources/bosh-io-stemcell-resource.tar.gz:
  object_id: 6709e19c-369b-4d0d-bf25-f7d655024c9f
  sha: !binary |-
    Y2E0OGFlMmRlM2EzYTQ2YzU4N2ZjNWNhZGYzYWY4Yzc1NGMyYzI0OA==
  size: 8407988
resources/bosh-io-release-resource.tar.gz:
  object_id: 8b247e46-8f37-4656-bda8-9fd65d05df98
  sha: !binary |-
    OTcyNThjMzAzOTVlMGQ4Y2YxYTdkMzZhNzE1MjMwZDBhZTg0MDVjYQ==
  size: 8409411
resources/bosh-deployment-resource.tar.gz:
  object_id: 9e23fc8f-14b9-41c2-944c-d2021389d6d3
  sha: !binary |-
    NWJjNzVhZjk0MGZmYmU2MDI4OTc1MmUzMmU4MjhmNGM2Mjg4YzI3NQ==
  size: 22129141
