---
golang_1.3/go1.3.linux-amd64.tar.gz:
  object_id: a0efd822-3cc4-4acf-af26-702cae02ff7a
  sha: b6b154933039987056ac307e20c25fa508a06ba6
  size: 51123994
postgresql/postgresql-9.3.4.tar.gz:
  object_id: a62f2cda-80fa-4daf-a59c-5acc9a6a3c2e
  sha: 9f80b3cfebc434ca0860fc8489923cea73456081
  size: 21865589
resources/archive-resource.tar.gz:
  object_id: b91d7f4c-701f-4ed2-bb6f-60cf25d2bc71
  sha: !binary |-
    OWE5Zjk5MzMxYmI0Y2ZhNTE4YmQ3OTNiMDM4MWVlZDVkYmYwMjMwZQ==
  size: 2549730
resources/time-resource.tar.gz:
  object_id: 1e6e46c8-3323-4fd0-a611-f4ee96d815b6
  sha: !binary |-
    NzdkZTNkODBhMWYwOGY3ODcxNTVmZjhkYzJkODhlMzI5ZTAzYjVkNA==
  size: 2518571
resources/semver-resource.tar.gz:
  object_id: 367a516c-3e29-4aad-a50a-782d47ec0ad4
  sha: !binary |-
    MzUzMjA2ZDZmZTYxMWNiMDEyNmZiMjNlMzkyNmY5OWFiYTMwNGI2Nw==
  size: 8893448
resources/s3-resource.tar.gz:
  object_id: 82b982a8-6314-4550-8e11-30e5e661835a
  sha: !binary |-
    NmJiOWNiNjdhYjQyNmU4OTZiYzlhYTBhNjA2NDE1YzA2YWFmNzliMw==
  size: 9103274
resources/tracker-resource.tar.gz:
  object_id: d04dabdd-7630-4079-a046-cd643ff4ab65
  sha: !binary |-
    Njg2ZGU2NWZiODgzYTNlOWUzMzQyZGQ3MmZjMzExNmI0YmNjMTRiNw==
  size: 13191976
resources/git-resource.tar.gz:
  object_id: 61d04909-98bd-4b91-9dae-b2af50e6ef90
  sha: !binary |-
    MDc1NTQzNDNkMWQzMDYxN2Q5MmFkZDI0OWY5MGQzYjA4NGRiZjBlZQ==
  size: 9155190
resources/docker-image-resource.tar.gz:
  object_id: f927a94b-d1b8-43a1-9037-72fef27f565b
  sha: !binary |-
    YmNmMDg0MWJjMTdiMzg1NGM4YTQ5N2IxNGI2YjAyODhmYmY1YTBiZA==
  size: 8069465
consul_0.4/consul:
  object_id: 854e5eba-0de6-4212-af07-c58dab9cfd3a
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
resources/vagrant-cloud-resource.tar.gz:
  object_id: 0cfd7222-bd5f-4f7e-93ad-5a4d8dd827aa
  sha: !binary |-
    YjUwODdhZDEyMmNjMjFhOTQ5ZDY0Mjk2M2Y3ZGNmOTIwNGJmMmE5Nw==
  size: 9154707
resources/cf-resource.tar.gz:
  object_id: 9377b9c0-c6aa-4a61-9ec7-1eef7df4a64f
  sha: !binary |-
    NjczZDVmMzhiN2RhMmI5OTJhZGYwZTA0MGU4MTM1ZjI3ZTJkYmE4NQ==
  size: 12570574
