name: concourse

director_uuid: (( merge ))

releases:
  - name: concourse
    version: latest

networks: (( merge ))

jobs: (( merge ))

meta:
  environment: ~

  stemcell:
    name: (( merge ))
    version: latest

compilation:
  workers: 6
  network: concourse
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

resource_pools:
  - name: atc
    network: concourse
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: postgresql
    network: concourse
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: glider
    network: concourse
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: turbines
    network: concourse
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
