---
name: concourse

director_uuid: (( merge ))

releases:
  - name: concourse
    version: latest

jobs:
  - name: atc
    templates:
      - name: atc
        release: concourse
      - name: glider
        release: concourse
      - name: consul-agent
        release: concourse
    instances: 1
    resource_pool: orchestration
    networks:
      - name: concourse
        static_ips: (( static_ips(0) ))
    properties:
      network_name: concourse
      atc:
        basic_auth_encrypted_password: ~
        basic_auth_username: ~
        config: (( merge ))
        postgresql:
          database: atc
          role: (( jobs.postgresql.properties.postgresql.roles.atc ))
      consul:
        agent:
          mode: server
          services:
            - name: atc
            - name: glider

  - name: postgresql
    templates:
      - name: postgresql
        release: concourse
      - name: consul-agent
        release: concourse
    instances: 1
    resource_pool: databases
    persistent_disk: 10240
    networks:
      - name: concourse
    properties:
      postgresql:
        databases:
          - name: atc
        roles:
          - name: atc
            password: (( merge ))
      consul:
        agent:
          servers:
            lan: (( jobs.atc.networks.concourse.static_ips ))
          services:
            - name: postgresql

  - name: turbine
    templates:
      - name: turbine
        release: concourse
      - name: warden
        release: concourse
      - name: consul-agent
        release: concourse
    instances: 1
    resource_pool: workers
    networks:
      - name: concourse
    properties:
      network_name: concourse
      consul:
        agent:
          servers:
            lan: (( jobs.atc.networks.concourse.static_ips ))
          services:
            - name: turbine

meta:
  stemcell:
    name: (( merge ))
    version: latest

networks: (( merge ))

compilation:
  workers: 6
  network: concourse
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

resource_pools:
  - name: orchestration
    network: concourse
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: databases
    network: concourse
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

  - name: workers
    network: concourse
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))
