meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

jobs:
  - name: redgreen
    instances: 0
    properties:
      redgreen:
        listen_address: 0.0.0.0:8153
        prole:
          address: (( jobs.prole.networks.room101.static_ips.[0] ":4637" ))

  - name: redis
    instances: 1
    networks:
      - name: room101
        static_ips: (( static_ips(1) ))

  - name: winston
    properties:
      winston:
        prole:
          address: (( jobs.prole.networks.room101.static_ips.[0] ":4637" ))
        redis:
          address: (( jobs.redis.networks.room101.static_ips.[0] ":6379" ))

  - name: prole
    instances: 1
    networks:
      - name: room101
        static_ips: (( static_ips(16) ))
    properties:
      warden:
        disk_quota_enabled: false

networks: (( merge ))
