meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

jobs:
  - name: glider
    instances: 0
    properties:
      glider:
        listen_address: 0.0.0.0:8153
        turbine:
          address: (( jobs.turbine.networks.concourse.static_ips.[0] ":4637" ))

  - name: postgresql
    instances: 1
    networks:
      - name: concourse
        static_ips: (( static_ips(1) ))

  - name: atc
    properties:
      atc:
        turbine:
          address: (( jobs.turbine.networks.concourse.static_ips.[0] ":4637" ))
        postgresql:
          address: (( jobs.postgresql.networks.concourse.static_ips.[0] ":5432" ))

  - name: turbine
    instances: 1
    networks:
      - name: concourse
        static_ips: (( static_ips(16) ))
    properties:
      warden:
        disk_quota_enabled: false

networks: (( merge ))
