meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: latest

  zones:
    z1: (( merge ))

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

compilation:
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( meta.zones.z1 ))

jobs:
  - name: consul_server
    instances: 1
    networks:
      - name: room101
        static_ips: (( static_ips(0) ))

networks: (( merge ))

resource_pools:
  - name: room101
    cloud_properties:
      instance_type: m1.medium
      availability_zone: (( meta.zones.z1 ))
      elbs: (( merge ))

  - name: proles
    cloud_properties:
      instance_type: c3.large
      availability_zone: (( meta.zones.z1 ))
      elbs: (( merge ))
