networks: (( merge ))

jobs:
  - name: redgreen
    templates:
      - name: redgreen
        release: room101
    instances: 1
    resource_pool: redgreen
    networks:
      - name: room101
        static_ips: ~
    properties:
      network_name: room101
      redgreen:
        listen_address: ~
        prole:
          address: (( merge ))

  - name: winston
    templates:
      - name: winston
        release: room101
    instances: 1
    resource_pool: winston
    networks:
      - name: room101
    properties:
      network_name: room101
      winston:
        listen_address: ~
        prole:
          address: (( merge ))
        redis: (( merge ))
        config: (( merge ))

  - name: prole
    templates:
      - name: prole
        release: room101
      - name: warden
        release: room101
    instances: 1
    resource_pool: proles
    networks:
      - name: room101
        static_ips: ~
    properties:
      network_name: room101
      warden: ~
      prole: ~
