networks: (( merge ))

jobs:
  - name: glider
    templates:
      - name: glider
        release: concourse
    instances: 1
    resource_pool: glider
    networks:
      - name: concourse
        static_ips: ~
    properties:
      network_name: concourse
      glider:
        listen_address: ~
        turbine:
          address: (( merge ))

  - name: postgresql
    templates:
      - name: postgresql
        release: concourse
    instances: 1
    resource_pool: postgresql
    persistent_disk: 1024
    networks:
      - name: concourse
        static_ips: ~
    properties:
      postgresql:
        databases:
          - name: atc
        roles:
          - name: atc
            password: (( merge ))

  - name: atc
    templates:
      - name: atc
        release: concourse
    instances: 1
    resource_pool: atc
    networks:
      - name: concourse
    properties:
      network_name: concourse
      atc:
        listen_address: ~
        turbine:
          address: (( merge ))
        postgresql:
          address: (( merge ))
          database: atc
          role: (( jobs.postgresql.properties.postgresql.roles.atc ))
        config: (( merge ))
        basic_auth_username: (( merge ))
        basic_auth_encrypted_password: (( merge ))

  - name: turbine
    templates:
      - name: turbine
        release: concourse
      - name: warden
        release: concourse
    instances: 1
    resource_pool: turbines
    networks:
      - name: concourse
        static_ips: ~
    properties:
      network_name: concourse
      warden: ~
      turbine: ~
