networks: (( merge ))

jobs:
  - name: glider
    templates:
      - name: glider
        release: concourse
    instances: 1
    resource_pool: glider
    networks:
      - name: concourse
        static_ips: ~
    properties:
      network_name: concourse
      glider:
        listen_address: ~
        turbine:
          address: (( merge ))

  - name: redis
    templates:
      - name: redis
        release: concourse
    instances: 1
    resource_pool: redis
    networks:
      - name: concourse
        static_ips: ~

  - name: atc
    templates:
      - name: atc
        release: concourse
    instances: 1
    resource_pool: atc
    networks:
      - name: concourse
    properties:
      network_name: concourse
      atc:
        listen_address: ~
        turbine:
          address: (( merge ))
        redis: (( merge ))
        config: (( merge ))
        basic_auth_username: (( merge ))
        basic_auth_encrypted_password: (( merge ))

  - name: turbine
    templates:
      - name: turbine
        release: concourse
      - name: warden
        release: concourse
    instances: 1
    resource_pool: turbines
    networks:
      - name: concourse
        static_ips: ~
    properties:
      network_name: concourse
      warden: ~
      turbine: ~
