---
image: concourse/testflight

env:
  - GOROOT=/usr/local/go
  - PATH=$GOROOT/bin:$PATH
  - GOPATH=/tmp/build/src/testflight
  - PATH=$GOPATH/bin:$PATH
  - DOCKER_REGISTRY_CONFIG=/docker-registry/config/config_sample.yml
  - SETTINGS_FLAVOR=dev

script: |
  set -e -x

  docker-registry &

  until curl http://127.0.0.1:5000; do
    echo waiting for registry on port 5000...
    sleep 1;
  done

  # bullshit
  mount -t tmpfs -o remount,size=1G none /dev/shm

  # realshit
  mkdir -p /var/lib/docker
  mount -t tmpfs -o size=1G none /var/lib/docker

  # cgroups for docker
  mkdir -p /sys/fs/cgroup
  cgroups-mount

  service docker.io start

  until [ -S /var/run/docker.sock ]; do
    echo fml
    sleep 0.5
  done

  pushd $GOPATH/resource-images
    docker.io build -t localhost:5000/raw-resource git
    docker.io push localhost:5000/raw-resource
  popd

  cd $GOPATH/src/github.com/concourse/testflight/

  go install github.com/onsi/ginkgo/ginkgo

  pushd $GOPATH/src/github.com/cloudfoundry-incubator/warden-linux
    make # compile wshd/etc.
    export WARDEN_BINPATH=$PWD/linux_backend/bin
  popd

  ginkgo -r -v
