---
resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/concourse/concourse
    branch: develop

- name: garden-linux-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/garden-linux-release
    branch: bump-and-force-aufs

- name: bin
  type: git
  source:
    uri: https://github.com/concourse/bin
    branch: master

- name: houdini
  type: git
  source:
    uri: https://github.com/vito/houdini
    branch: master

- name: bin-releases
  type: github-release
  source:
    user: concourse
    repository: bin
    access_token: {{release-token}}

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: concourse
    - get: garden-linux-release
    - get: bin
    - get: houdini
  - aggregate:
    - task: build-linux
      file: bin/ci/build-linux.yml
    - task: build-darwin
      file: bin/ci/build-darwin.yml
    - task: build-windows
      file: bin/ci/build-windows.yml
  - task: build-release
    file: bin/ci/build-release.yml
  - put: bin-releases
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs: [release/artifacts/*]
