---
resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/concourse/concourse
    branch: guardian

- name: guardian-release
  type: git
  source:
    uri: https://github.com/vito/guardian-release
    branch: concourse

- name: bin
  type: git
  source:
    uri: https://github.com/concourse/bin
    branch: guardian

- name: houdini
  type: git
  source:
    uri: https://github.com/vito/houdini
    branch: master

- name: bin-releases
  type: github-release
  source:
    user: vito
    repository: bin
    access_token: {{release-token}}

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: concourse
    - get: guardian-release
    - get: bin
    - get: houdini
  - task: make-up-final-version
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: {repository: busybox}

      outputs:
      - name: final-version

      run:
        path: sh
        args: [-c, 'echo 0.0.0 > final-version/version']
  - task: build-cli-artifacts
    file: bin/ci/build-cli-artifacts.yml
  - aggregate:
    - task: build-linux
      file: bin/ci/build-linux.yml
      output_mapping: {binary: linux-binary}
    - task: build-darwin
      file: bin/ci/build-darwin.yml
      output_mapping: {binary: darwin-binary}
    - task: build-windows
      file: bin/ci/build-windows.yml
      output_mapping: {binary: windows-binary}
  - task: build-release
    file: bin/ci/build-release.yml
  - put: bin-releases
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs: [release/artifacts/*]
