---
resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/concourse/concourse
    branch: develop

- name: garden-linux-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/garden-linux-release
    branch: bump-and-force-aufs

- name: concourse-bin
  type: git
  source:
    uri: https://github.com/vito/concourse-bin
    branch: master

- name: houdini
  type: git
  source:
    uri: https://github.com/vito/houdini
    branch: master

- name: concourse-bin-releases
  type: github-release
  source:
    user: vito
    repository: concourse-bin
    access_token: {{release-token}}

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: concourse
    - get: garden-linux-release
    - get: concourse-bin
    - get: houdini
  - aggregate:
    - task: build-linux
      file: concourse-bin/ci/build-linux.yml
    - task: build-darwin
      file: concourse-bin/ci/build-darwin.yml
    - task: build-windows
      file: concourse-bin/ci/build-windows.yml
  - task: build-release
    file: concourse-bin/ci/build-release.yml
  - put: concourse-bin-releases
    params:
      name: release/name
      tag: release/tag
      body: release/body
      globs: [release/artifacts/*]
