---
azs:
- name: z1

networks:
- name: topgun
  subnets:
  - az: z1
    range: 10.234.0.0/16
    gateway: 10.234.0.1
    static:
    - 10.234.0.14
    - 10.234.0.15

- name: testflight
  subnets:
  - az: z1
    gateway: 10.244.0.1
    range: 10.244.0.0/16
    static:
    - 10.244.15.2
    - 10.244.16.2
    - 10.244.17.2
    - 10.244.18.2
    - 10.244.19.2
    - 10.244.20.2
    - 10.244.21.2
    - 10.244.22.2
    - 10.244.23.2
    - 10.244.24.2
vm_types:
- name: topgun
  network: topgun
- name: testflight
  network: testflight

compilation:
  az: z1
  workers: 3
  network: topgun
